// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.2
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _iosc_iosPulseThread_HH_
#define _iosc_iosPulseThread_HH_

#include "systemc.h"
#include "AESL_pkg.h"


namespace ap_rtl {

struct iosc_iosPulseThread : public sc_module {
    // Port declarations 8
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_lv<4> > iosc_secCounter_V_i;
    sc_out< sc_lv<4> > iosc_secCounter_V_o;
    sc_out< sc_logic > iosc_secCounter_V_o_ap_vld;
    sc_in< sc_lv<32> > iosc_counter_clk_V_i;
    sc_out< sc_lv<32> > iosc_counter_clk_V_o;
    sc_out< sc_logic > iosc_counter_clk_V_o_ap_vld;


    // Module declarations
    iosc_iosPulseThread(sc_module_name name);
    SC_HAS_PROCESS(iosc_iosPulseThread);

    ~iosc_iosPulseThread();

    sc_trace_file* mVcdFile;

    sc_signal< sc_lv<1> > tmp_2_fu_118_p2;
    sc_signal< sc_lv<1> > tmp_2_reg_131;
    sc_signal< sc_lv<3> > ap_CS_fsm;
    sc_signal< sc_logic > ap_CS_fsm_state2;
    sc_signal< sc_lv<32> > iosc_counter_clk_V_a_fu_111_p2;
    sc_signal< sc_logic > ap_CS_fsm_state3;
    sc_signal< sc_lv<3> > ap_NS_fsm;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<3> ap_ST_fsm_state2;
    static const sc_lv<3> ap_ST_fsm_state3;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<32> ap_const_lv32_2;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<32> ap_const_lv32_2FAF07F;
    static const sc_lv<4> ap_const_lv4_1;
    static const bool ap_const_boolean_1;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_ap_CS_fsm_state2();
    void thread_ap_CS_fsm_state3();
    void thread_iosc_counter_clk_V_a_fu_111_p2();
    void thread_iosc_counter_clk_V_o();
    void thread_iosc_counter_clk_V_o_ap_vld();
    void thread_iosc_secCounter_V_o();
    void thread_iosc_secCounter_V_o_ap_vld();
    void thread_tmp_2_fu_118_p2();
    void thread_ap_NS_fsm();
};

}

using namespace ap_rtl;

#endif
