// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.2
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// ==============================================================

extern void AESL_WRAP_differentiate (
unsigned char img[64][48],
ap_int<3> window[3][3],
ap_uint<15> res[62][46]);
