<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
<!DOCTYPE boost_serialization>
<boost_serialization signature="serialization::archive" version="14">
  <syndb class_id="0" tracking_level="0" version="0">
    <userIPLatency>-1</userIPLatency>
    <userIPName/>
    <cdfg class_id="1" tracking_level="1" version="0" object_id="_0">
      <name>iosc_iosPulseThread</name>
      <ret_bitwidth>0</ret_bitwidth>
      <ports class_id="2" tracking_level="0" version="0">
        <count>2</count>
        <item_version>0</item_version>
        <item class_id="3" tracking_level="1" version="0" object_id="_1">
          <Value class_id="4" tracking_level="0" version="0">
            <Obj class_id="5" tracking_level="0" version="0">
              <type>1</type>
              <id>8</id>
              <name>iosc_secCounter_V</name>
              <fileName/>
              <fileDirectory/>
              <lineNumber>0</lineNumber>
              <contextFuncName/>
              <inlineStackInfo class_id="6" tracking_level="0" version="0">
                <count>0</count>
                <item_version>0</item_version>
              </inlineStackInfo>
              <originalName>iosc.secCounter.V</originalName>
              <rtlName/>
              <coreName/>
            </Obj>
            <bitwidth>4</bitwidth>
          </Value>
          <direction>2</direction>
          <if_type>0</if_type>
          <array_size>0</array_size>
          <bit_vecs class_id="7" tracking_level="0" version="0">
            <count>0</count>
            <item_version>0</item_version>
          </bit_vecs>
        </item>
        <item class_id_reference="3" object_id="_2">
          <Value>
            <Obj>
              <type>1</type>
              <id>9</id>
              <name>iosc_counter_clk_V</name>
              <fileName/>
              <fileDirectory/>
              <lineNumber>0</lineNumber>
              <contextFuncName/>
              <inlineStackInfo>
                <count>0</count>
                <item_version>0</item_version>
              </inlineStackInfo>
              <originalName>iosc.counter_clk.V</originalName>
              <rtlName/>
              <coreName/>
            </Obj>
            <bitwidth>32</bitwidth>
          </Value>
          <direction>2</direction>
          <if_type>0</if_type>
          <array_size>0</array_size>
          <bit_vecs>
            <count>0</count>
            <item_version>0</item_version>
          </bit_vecs>
        </item>
      </ports>
      <nodes class_id="8" tracking_level="0" version="0">
        <count>13</count>
        <item_version>0</item_version>
        <item class_id="9" tracking_level="1" version="0" object_id="_3">
          <Value>
            <Obj>
              <type>0</type>
              <id>31</id>
              <name/>
              <fileName>ios.cpp</fileName>
              <fileDirectory>..</fileDirectory>
              <lineNumber>45</lineNumber>
              <contextFuncName>iosPulseThread</contextFuncName>
              <inlineStackInfo>
                <count>1</count>
                <item_version>0</item_version>
                <item class_id="10" tracking_level="0" version="0">
                  <first>C:\Users\krabs\source\repos\ERTS\Assignment_2\ex7\SC_IO</first>
                  <second class_id="11" tracking_level="0" version="0">
                    <count>1</count>
                    <item_version>0</item_version>
                    <item class_id="12" tracking_level="0" version="0">
                      <first class_id="13" tracking_level="0" version="0">
                        <first>ios.cpp</first>
                        <second>iosPulseThread</second>
                      </first>
                      <second>45</second>
                    </item>
                  </second>
                </item>
              </inlineStackInfo>
              <originalName/>
              <rtlName/>
              <coreName/>
            </Obj>
            <bitwidth>0</bitwidth>
          </Value>
          <oprand_edges>
            <count>1</count>
            <item_version>0</item_version>
            <item>48</item>
          </oprand_edges>
          <opcode>br</opcode>
          <m_Display>0</m_Display>
        </item>
        <item class_id_reference="9" object_id="_4">
          <Value>
            <Obj>
              <type>0</type>
              <id>33</id>
              <name>iosc_counter_clk_V_r</name>
              <fileName>ios.cpp</fileName>
              <fileDirectory>..</fileDirectory>
              <lineNumber>34</lineNumber>
              <contextFuncName>iosPulseThread</contextFuncName>
              <inlineStackInfo>
                <count>1</count>
                <item_version>0</item_version>
                <item>
                  <first>C:\Users\krabs\source\repos\ERTS\Assignment_2\ex7\SC_IO</first>
                  <second>
                    <count>1</count>
                    <item_version>0</item_version>
                    <item>
                      <first>
                        <first>ios.cpp</first>
                        <second>iosPulseThread</second>
                      </first>
                      <second>34</second>
                    </item>
                  </second>
                </item>
              </inlineStackInfo>
              <originalName/>
              <rtlName/>
              <coreName/>
            </Obj>
            <bitwidth>32</bitwidth>
          </Value>
          <oprand_edges>
            <count>2</count>
            <item_version>0</item_version>
            <item>50</item>
            <item>51</item>
          </oprand_edges>
          <opcode>read</opcode>
          <m_Display>0</m_Display>
        </item>
        <item class_id_reference="9" object_id="_5">
          <Value>
            <Obj>
              <type>0</type>
              <id>34</id>
              <name>iosc_counter_clk_V_a</name>
              <fileName>ios.cpp</fileName>
              <fileDirectory>..</fileDirectory>
              <lineNumber>34</lineNumber>
              <contextFuncName>iosPulseThread</contextFuncName>
              <inlineStackInfo>
                <count>1</count>
                <item_version>0</item_version>
                <item>
                  <first>C:\Users\krabs\source\repos\ERTS\Assignment_2\ex7\SC_IO</first>
                  <second>
                    <count>1</count>
                    <item_version>0</item_version>
                    <item>
                      <first>
                        <first>ios.cpp</first>
                        <second>iosPulseThread</second>
                      </first>
                      <second>34</second>
                    </item>
                  </second>
                </item>
              </inlineStackInfo>
              <originalName/>
              <rtlName>iosc_counter_clk_V_a_fu_111_p2</rtlName>
              <coreName/>
            </Obj>
            <bitwidth>32</bitwidth>
          </Value>
          <oprand_edges>
            <count>2</count>
            <item_version>0</item_version>
            <item>52</item>
            <item>54</item>
          </oprand_edges>
          <opcode>add</opcode>
          <m_Display>0</m_Display>
        </item>
        <item class_id_reference="9" object_id="_6">
          <Value>
            <Obj>
              <type>0</type>
              <id>35</id>
              <name/>
              <fileName>ios.cpp</fileName>
              <fileDirectory>..</fileDirectory>
              <lineNumber>34</lineNumber>
              <contextFuncName>iosPulseThread</contextFuncName>
              <inlineStackInfo>
                <count>1</count>
                <item_version>0</item_version>
                <item>
                  <first>C:\Users\krabs\source\repos\ERTS\Assignment_2\ex7\SC_IO</first>
                  <second>
                    <count>1</count>
                    <item_version>0</item_version>
                    <item>
                      <first>
                        <first>ios.cpp</first>
                        <second>iosPulseThread</second>
                      </first>
                      <second>34</second>
                    </item>
                  </second>
                </item>
              </inlineStackInfo>
              <originalName/>
              <rtlName/>
              <coreName/>
            </Obj>
            <bitwidth>0</bitwidth>
          </Value>
          <oprand_edges>
            <count>4</count>
            <item_version>0</item_version>
            <item>56</item>
            <item>57</item>
            <item>58</item>
            <item>200</item>
          </oprand_edges>
          <opcode>write</opcode>
          <m_Display>0</m_Display>
        </item>
        <item class_id_reference="9" object_id="_7">
          <Value>
            <Obj>
              <type>0</type>
              <id>36</id>
              <name>tmp_2</name>
              <fileName>ios.cpp</fileName>
              <fileDirectory>..</fileDirectory>
              <lineNumber>34</lineNumber>
              <contextFuncName>iosPulseThread</contextFuncName>
              <inlineStackInfo>
                <count>1</count>
                <item_version>0</item_version>
                <item>
                  <first>C:\Users\krabs\source\repos\ERTS\Assignment_2\ex7\SC_IO</first>
                  <second>
                    <count>1</count>
                    <item_version>0</item_version>
                    <item>
                      <first>
                        <first>ios.cpp</first>
                        <second>iosPulseThread</second>
                      </first>
                      <second>34</second>
                    </item>
                  </second>
                </item>
              </inlineStackInfo>
              <originalName/>
              <rtlName>tmp_2_fu_118_p2</rtlName>
              <coreName/>
            </Obj>
            <bitwidth>1</bitwidth>
          </Value>
          <oprand_edges>
            <count>2</count>
            <item_version>0</item_version>
            <item>59</item>
            <item>61</item>
          </oprand_edges>
          <opcode>icmp</opcode>
          <m_Display>0</m_Display>
        </item>
        <item class_id_reference="9" object_id="_8">
          <Value>
            <Obj>
              <type>0</type>
              <id>37</id>
              <name/>
              <fileName>ios.cpp</fileName>
              <fileDirectory>..</fileDirectory>
              <lineNumber>34</lineNumber>
              <contextFuncName>iosPulseThread</contextFuncName>
              <inlineStackInfo>
                <count>1</count>
                <item_version>0</item_version>
                <item>
                  <first>C:\Users\krabs\source\repos\ERTS\Assignment_2\ex7\SC_IO</first>
                  <second>
                    <count>1</count>
                    <item_version>0</item_version>
                    <item>
                      <first>
                        <first>ios.cpp</first>
                        <second>iosPulseThread</second>
                      </first>
                      <second>34</second>
                    </item>
                  </second>
                </item>
              </inlineStackInfo>
              <originalName/>
              <rtlName/>
              <coreName/>
            </Obj>
            <bitwidth>0</bitwidth>
          </Value>
          <oprand_edges>
            <count>3</count>
            <item_version>0</item_version>
            <item>62</item>
            <item>63</item>
            <item>64</item>
          </oprand_edges>
          <opcode>br</opcode>
          <m_Display>0</m_Display>
        </item>
        <item class_id_reference="9" object_id="_9">
          <Value>
            <Obj>
              <type>0</type>
              <id>39</id>
              <name>iosc_secCounter_V_re</name>
              <fileName>ios.cpp</fileName>
              <fileDirectory>..</fileDirectory>
              <lineNumber>36</lineNumber>
              <contextFuncName>iosPulseThread</contextFuncName>
              <inlineStackInfo>
                <count>1</count>
                <item_version>0</item_version>
                <item>
                  <first>C:\Users\krabs\source\repos\ERTS\Assignment_2\ex7\SC_IO</first>
                  <second>
                    <count>1</count>
                    <item_version>0</item_version>
                    <item>
                      <first>
                        <first>ios.cpp</first>
                        <second>iosPulseThread</second>
                      </first>
                      <second>36</second>
                    </item>
                  </second>
                </item>
              </inlineStackInfo>
              <originalName/>
              <rtlName/>
              <coreName/>
            </Obj>
            <bitwidth>4</bitwidth>
          </Value>
          <oprand_edges>
            <count>2</count>
            <item_version>0</item_version>
            <item>66</item>
            <item>67</item>
          </oprand_edges>
          <opcode>read</opcode>
          <m_Display>0</m_Display>
        </item>
        <item class_id_reference="9" object_id="_10">
          <Value>
            <Obj>
              <type>0</type>
              <id>40</id>
              <name>tmp_3</name>
              <fileName>ios.cpp</fileName>
              <fileDirectory>..</fileDirectory>
              <lineNumber>36</lineNumber>
              <contextFuncName>iosPulseThread</contextFuncName>
              <inlineStackInfo>
                <count>1</count>
                <item_version>0</item_version>
                <item>
                  <first>C:\Users\krabs\source\repos\ERTS\Assignment_2\ex7\SC_IO</first>
                  <second>
                    <count>1</count>
                    <item_version>0</item_version>
                    <item>
                      <first>
                        <first>ios.cpp</first>
                        <second>iosPulseThread</second>
                      </first>
                      <second>36</second>
                    </item>
                  </second>
                </item>
              </inlineStackInfo>
              <originalName/>
              <rtlName>iosc_secCounter_V_o</rtlName>
              <coreName/>
            </Obj>
            <bitwidth>4</bitwidth>
          </Value>
          <oprand_edges>
            <count>2</count>
            <item_version>0</item_version>
            <item>68</item>
            <item>70</item>
          </oprand_edges>
          <opcode>add</opcode>
          <m_Display>0</m_Display>
        </item>
        <item class_id_reference="9" object_id="_11">
          <Value>
            <Obj>
              <type>0</type>
              <id>41</id>
              <name/>
              <fileName>ios.cpp</fileName>
              <fileDirectory>..</fileDirectory>
              <lineNumber>36</lineNumber>
              <contextFuncName>iosPulseThread</contextFuncName>
              <inlineStackInfo>
                <count>1</count>
                <item_version>0</item_version>
                <item>
                  <first>C:\Users\krabs\source\repos\ERTS\Assignment_2\ex7\SC_IO</first>
                  <second>
                    <count>1</count>
                    <item_version>0</item_version>
                    <item>
                      <first>
                        <first>ios.cpp</first>
                        <second>iosPulseThread</second>
                      </first>
                      <second>36</second>
                    </item>
                  </second>
                </item>
              </inlineStackInfo>
              <originalName/>
              <rtlName/>
              <coreName/>
            </Obj>
            <bitwidth>0</bitwidth>
          </Value>
          <oprand_edges>
            <count>4</count>
            <item_version>0</item_version>
            <item>72</item>
            <item>73</item>
            <item>74</item>
            <item>201</item>
          </oprand_edges>
          <opcode>write</opcode>
          <m_Display>0</m_Display>
        </item>
        <item class_id_reference="9" object_id="_12">
          <Value>
            <Obj>
              <type>0</type>
              <id>42</id>
              <name/>
              <fileName>ios.cpp</fileName>
              <fileDirectory>..</fileDirectory>
              <lineNumber>37</lineNumber>
              <contextFuncName>iosPulseThread</contextFuncName>
              <inlineStackInfo>
                <count>1</count>
                <item_version>0</item_version>
                <item>
                  <first>C:\Users\krabs\source\repos\ERTS\Assignment_2\ex7\SC_IO</first>
                  <second>
                    <count>1</count>
                    <item_version>0</item_version>
                    <item>
                      <first>
                        <first>ios.cpp</first>
                        <second>iosPulseThread</second>
                      </first>
                      <second>37</second>
                    </item>
                  </second>
                </item>
              </inlineStackInfo>
              <originalName/>
              <rtlName/>
              <coreName/>
            </Obj>
            <bitwidth>0</bitwidth>
          </Value>
          <oprand_edges>
            <count>5</count>
            <item_version>0</item_version>
            <item>75</item>
            <item>76</item>
            <item>78</item>
            <item>202</item>
            <item>203</item>
          </oprand_edges>
          <opcode>write</opcode>
          <m_Display>0</m_Display>
        </item>
        <item class_id_reference="9" object_id="_13">
          <Value>
            <Obj>
              <type>0</type>
              <id>43</id>
              <name/>
              <fileName>ios.cpp</fileName>
              <fileDirectory>..</fileDirectory>
              <lineNumber>40</lineNumber>
              <contextFuncName>iosPulseThread</contextFuncName>
              <inlineStackInfo>
                <count>1</count>
                <item_version>0</item_version>
                <item>
                  <first>C:\Users\krabs\source\repos\ERTS\Assignment_2\ex7\SC_IO</first>
                  <second>
                    <count>1</count>
                    <item_version>0</item_version>
                    <item>
                      <first>
                        <first>ios.cpp</first>
                        <second>iosPulseThread</second>
                      </first>
                      <second>40</second>
                    </item>
                  </second>
                </item>
              </inlineStackInfo>
              <originalName/>
              <rtlName/>
              <coreName/>
            </Obj>
            <bitwidth>0</bitwidth>
          </Value>
          <oprand_edges>
            <count>1</count>
            <item_version>0</item_version>
            <item>79</item>
          </oprand_edges>
          <opcode>br</opcode>
          <m_Display>0</m_Display>
        </item>
        <item class_id_reference="9" object_id="_14">
          <Value>
            <Obj>
              <type>0</type>
              <id>45</id>
              <name/>
              <fileName>ios.cpp</fileName>
              <fileDirectory>..</fileDirectory>
              <lineNumber>41</lineNumber>
              <contextFuncName>iosPulseThread</contextFuncName>
              <inlineStackInfo>
                <count>1</count>
                <item_version>0</item_version>
                <item>
                  <first>C:\Users\krabs\source\repos\ERTS\Assignment_2\ex7\SC_IO</first>
                  <second>
                    <count>1</count>
                    <item_version>0</item_version>
                    <item>
                      <first>
                        <first>ios.cpp</first>
                        <second>iosPulseThread</second>
                      </first>
                      <second>41</second>
                    </item>
                  </second>
                </item>
              </inlineStackInfo>
              <originalName/>
              <rtlName/>
              <coreName/>
            </Obj>
            <bitwidth>0</bitwidth>
          </Value>
          <oprand_edges>
            <count>2</count>
            <item_version>0</item_version>
            <item>81</item>
            <item>82</item>
          </oprand_edges>
          <opcode>wait</opcode>
          <m_Display>0</m_Display>
        </item>
        <item class_id_reference="9" object_id="_15">
          <Value>
            <Obj>
              <type>0</type>
              <id>46</id>
              <name/>
              <fileName>ios.cpp</fileName>
              <fileDirectory>..</fileDirectory>
              <lineNumber>42</lineNumber>
              <contextFuncName>iosPulseThread</contextFuncName>
              <inlineStackInfo>
                <count>1</count>
                <item_version>0</item_version>
                <item>
                  <first>C:\Users\krabs\source\repos\ERTS\Assignment_2\ex7\SC_IO</first>
                  <second>
                    <count>1</count>
                    <item_version>0</item_version>
                    <item>
                      <first>
                        <first>ios.cpp</first>
                        <second>iosPulseThread</second>
                      </first>
                      <second>42</second>
                    </item>
                  </second>
                </item>
              </inlineStackInfo>
              <originalName/>
              <rtlName/>
              <coreName/>
            </Obj>
            <bitwidth>0</bitwidth>
          </Value>
          <oprand_edges>
            <count>1</count>
            <item_version>0</item_version>
            <item>83</item>
          </oprand_edges>
          <opcode>br</opcode>
          <m_Display>0</m_Display>
        </item>
      </nodes>
      <consts class_id="15" tracking_level="0" version="0">
        <count>4</count>
        <item_version>0</item_version>
        <item class_id="16" tracking_level="1" version="0" object_id="_16">
          <Value>
            <Obj>
              <type>2</type>
              <id>53</id>
              <name>empty</name>
              <fileName/>
              <fileDirectory/>
              <lineNumber>0</lineNumber>
              <contextFuncName/>
              <inlineStackInfo>
                <count>0</count>
                <item_version>0</item_version>
              </inlineStackInfo>
              <originalName/>
              <rtlName/>
              <coreName/>
            </Obj>
            <bitwidth>32</bitwidth>
          </Value>
          <const_type>0</const_type>
          <content>1</content>
        </item>
        <item class_id_reference="16" object_id="_17">
          <Value>
            <Obj>
              <type>2</type>
              <id>60</id>
              <name>empty</name>
              <fileName/>
              <fileDirectory/>
              <lineNumber>0</lineNumber>
              <contextFuncName/>
              <inlineStackInfo>
                <count>0</count>
                <item_version>0</item_version>
              </inlineStackInfo>
              <originalName/>
              <rtlName/>
              <coreName/>
            </Obj>
            <bitwidth>32</bitwidth>
          </Value>
          <const_type>0</const_type>
          <content>49999999</content>
        </item>
        <item class_id_reference="16" object_id="_18">
          <Value>
            <Obj>
              <type>2</type>
              <id>69</id>
              <name>empty</name>
              <fileName/>
              <fileDirectory/>
              <lineNumber>0</lineNumber>
              <contextFuncName/>
              <inlineStackInfo>
                <count>0</count>
                <item_version>0</item_version>
              </inlineStackInfo>
              <originalName/>
              <rtlName/>
              <coreName/>
            </Obj>
            <bitwidth>4</bitwidth>
          </Value>
          <const_type>0</const_type>
          <content>1</content>
        </item>
        <item class_id_reference="16" object_id="_19">
          <Value>
            <Obj>
              <type>2</type>
              <id>77</id>
              <name>empty</name>
              <fileName/>
              <fileDirectory/>
              <lineNumber>0</lineNumber>
              <contextFuncName/>
              <inlineStackInfo>
                <count>0</count>
                <item_version>0</item_version>
              </inlineStackInfo>
              <originalName/>
              <rtlName/>
              <coreName/>
            </Obj>
            <bitwidth>32</bitwidth>
          </Value>
          <const_type>0</const_type>
          <content>0</content>
        </item>
      </consts>
      <blocks class_id="17" tracking_level="0" version="0">
        <count>4</count>
        <item_version>0</item_version>
        <item class_id="18" tracking_level="1" version="0" object_id="_20">
          <Obj>
            <type>3</type>
            <id>32</id>
            <name/>
            <fileName/>
            <fileDirectory/>
            <lineNumber>0</lineNumber>
            <contextFuncName/>
            <inlineStackInfo>
              <count>0</count>
              <item_version>0</item_version>
            </inlineStackInfo>
            <originalName/>
            <rtlName/>
            <coreName/>
          </Obj>
          <node_objs>
            <count>1</count>
            <item_version>0</item_version>
            <item>31</item>
          </node_objs>
        </item>
        <item class_id_reference="18" object_id="_21">
          <Obj>
            <type>3</type>
            <id>38</id>
            <name/>
            <fileName/>
            <fileDirectory/>
            <lineNumber>0</lineNumber>
            <contextFuncName/>
            <inlineStackInfo>
              <count>0</count>
              <item_version>0</item_version>
            </inlineStackInfo>
            <originalName/>
            <rtlName/>
            <coreName/>
          </Obj>
          <node_objs>
            <count>5</count>
            <item_version>0</item_version>
            <item>33</item>
            <item>34</item>
            <item>35</item>
            <item>36</item>
            <item>37</item>
          </node_objs>
        </item>
        <item class_id_reference="18" object_id="_22">
          <Obj>
            <type>3</type>
            <id>44</id>
            <name/>
            <fileName/>
            <fileDirectory/>
            <lineNumber>0</lineNumber>
            <contextFuncName/>
            <inlineStackInfo>
              <count>0</count>
              <item_version>0</item_version>
            </inlineStackInfo>
            <originalName/>
            <rtlName/>
            <coreName/>
          </Obj>
          <node_objs>
            <count>5</count>
            <item_version>0</item_version>
            <item>39</item>
            <item>40</item>
            <item>41</item>
            <item>42</item>
            <item>43</item>
          </node_objs>
        </item>
        <item class_id_reference="18" object_id="_23">
          <Obj>
            <type>3</type>
            <id>47</id>
            <name>_ZN7_ap_sc_7sc_core4waitEi.exit</name>
            <fileName/>
            <fileDirectory/>
            <lineNumber>0</lineNumber>
            <contextFuncName/>
            <inlineStackInfo>
              <count>0</count>
              <item_version>0</item_version>
            </inlineStackInfo>
            <originalName/>
            <rtlName/>
            <coreName/>
          </Obj>
          <node_objs>
            <count>2</count>
            <item_version>0</item_version>
            <item>45</item>
            <item>46</item>
          </node_objs>
        </item>
      </blocks>
      <edges class_id="19" tracking_level="0" version="0">
        <count>30</count>
        <item_version>0</item_version>
        <item class_id="20" tracking_level="1" version="0" object_id="_24">
          <id>48</id>
          <edge_type>2</edge_type>
          <source_obj>38</source_obj>
          <sink_obj>31</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_25">
          <id>51</id>
          <edge_type>1</edge_type>
          <source_obj>9</source_obj>
          <sink_obj>33</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_26">
          <id>52</id>
          <edge_type>1</edge_type>
          <source_obj>33</source_obj>
          <sink_obj>34</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_27">
          <id>54</id>
          <edge_type>1</edge_type>
          <source_obj>53</source_obj>
          <sink_obj>34</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_28">
          <id>57</id>
          <edge_type>1</edge_type>
          <source_obj>9</source_obj>
          <sink_obj>35</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_29">
          <id>58</id>
          <edge_type>1</edge_type>
          <source_obj>34</source_obj>
          <sink_obj>35</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_30">
          <id>59</id>
          <edge_type>1</edge_type>
          <source_obj>34</source_obj>
          <sink_obj>36</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_31">
          <id>61</id>
          <edge_type>1</edge_type>
          <source_obj>60</source_obj>
          <sink_obj>36</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_32">
          <id>62</id>
          <edge_type>1</edge_type>
          <source_obj>36</source_obj>
          <sink_obj>37</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_33">
          <id>63</id>
          <edge_type>2</edge_type>
          <source_obj>47</source_obj>
          <sink_obj>37</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_34">
          <id>64</id>
          <edge_type>2</edge_type>
          <source_obj>44</source_obj>
          <sink_obj>37</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_35">
          <id>67</id>
          <edge_type>1</edge_type>
          <source_obj>8</source_obj>
          <sink_obj>39</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_36">
          <id>68</id>
          <edge_type>1</edge_type>
          <source_obj>39</source_obj>
          <sink_obj>40</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_37">
          <id>70</id>
          <edge_type>1</edge_type>
          <source_obj>69</source_obj>
          <sink_obj>40</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_38">
          <id>73</id>
          <edge_type>1</edge_type>
          <source_obj>8</source_obj>
          <sink_obj>41</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_39">
          <id>74</id>
          <edge_type>1</edge_type>
          <source_obj>40</source_obj>
          <sink_obj>41</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_40">
          <id>76</id>
          <edge_type>1</edge_type>
          <source_obj>9</source_obj>
          <sink_obj>42</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_41">
          <id>78</id>
          <edge_type>1</edge_type>
          <source_obj>77</source_obj>
          <sink_obj>42</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_42">
          <id>79</id>
          <edge_type>2</edge_type>
          <source_obj>47</source_obj>
          <sink_obj>43</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_43">
          <id>82</id>
          <edge_type>1</edge_type>
          <source_obj>53</source_obj>
          <sink_obj>45</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_44">
          <id>83</id>
          <edge_type>2</edge_type>
          <source_obj>38</source_obj>
          <sink_obj>46</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_45">
          <id>195</id>
          <edge_type>2</edge_type>
          <source_obj>32</source_obj>
          <sink_obj>38</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_46">
          <id>196</id>
          <edge_type>2</edge_type>
          <source_obj>38</source_obj>
          <sink_obj>44</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_47">
          <id>197</id>
          <edge_type>2</edge_type>
          <source_obj>38</source_obj>
          <sink_obj>47</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_48">
          <id>198</id>
          <edge_type>2</edge_type>
          <source_obj>44</source_obj>
          <sink_obj>47</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_49">
          <id>199</id>
          <edge_type>2</edge_type>
          <source_obj>47</source_obj>
          <sink_obj>38</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_50">
          <id>200</id>
          <edge_type>4</edge_type>
          <source_obj>33</source_obj>
          <sink_obj>35</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_51">
          <id>201</id>
          <edge_type>4</edge_type>
          <source_obj>39</source_obj>
          <sink_obj>41</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_52">
          <id>202</id>
          <edge_type>4</edge_type>
          <source_obj>33</source_obj>
          <sink_obj>42</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_53">
          <id>203</id>
          <edge_type>4</edge_type>
          <source_obj>35</source_obj>
          <sink_obj>42</sink_obj>
        </item>
      </edges>
    </cdfg>
    <cdfg_regions class_id="21" tracking_level="0" version="0">
      <count>3</count>
      <item_version>0</item_version>
      <item class_id="22" tracking_level="1" version="0" object_id="_54">
        <mId>1</mId>
        <mTag>iosc::iosPulseThread</mTag>
        <mType>0</mType>
        <sub_regions>
          <count>2</count>
          <item_version>0</item_version>
          <item>2</item>
          <item>3</item>
        </sub_regions>
        <basic_blocks>
          <count>0</count>
          <item_version>0</item_version>
        </basic_blocks>
        <mII>-1</mII>
        <mDepth>-1</mDepth>
        <mMinTripCount>-1</mMinTripCount>
        <mMaxTripCount>-1</mMaxTripCount>
        <mMinLatency>3</mMinLatency>
        <mMaxLatency>-1</mMaxLatency>
        <mIsDfPipe>0</mIsDfPipe>
        <mDfPipe class_id="-1"/>
      </item>
      <item class_id_reference="22" object_id="_55">
        <mId>2</mId>
        <mTag>Entry</mTag>
        <mType>0</mType>
        <sub_regions>
          <count>0</count>
          <item_version>0</item_version>
        </sub_regions>
        <basic_blocks>
          <count>1</count>
          <item_version>0</item_version>
          <item>32</item>
        </basic_blocks>
        <mII>-1</mII>
        <mDepth>-1</mDepth>
        <mMinTripCount>-1</mMinTripCount>
        <mMaxTripCount>-1</mMaxTripCount>
        <mMinLatency>0</mMinLatency>
        <mMaxLatency>-1</mMaxLatency>
        <mIsDfPipe>0</mIsDfPipe>
        <mDfPipe class_id="-1"/>
      </item>
      <item class_id_reference="22" object_id="_56">
        <mId>3</mId>
        <mTag>Loop 1</mTag>
        <mType>1</mType>
        <sub_regions>
          <count>0</count>
          <item_version>0</item_version>
        </sub_regions>
        <basic_blocks>
          <count>3</count>
          <item_version>0</item_version>
          <item>38</item>
          <item>44</item>
          <item>47</item>
        </basic_blocks>
        <mII>-1</mII>
        <mDepth>-1</mDepth>
        <mMinTripCount>-1</mMinTripCount>
        <mMaxTripCount>-1</mMaxTripCount>
        <mMinLatency>2</mMinLatency>
        <mMaxLatency>-1</mMaxLatency>
        <mIsDfPipe>0</mIsDfPipe>
        <mDfPipe class_id="-1"/>
      </item>
    </cdfg_regions>
    <fsm class_id="24" tracking_level="1" version="0" object_id="_57">
      <states class_id="25" tracking_level="0" version="0">
        <count>3</count>
        <item_version>0</item_version>
        <item class_id="26" tracking_level="1" version="0" object_id="_58">
          <id>1</id>
          <operations class_id="27" tracking_level="0" version="0">
            <count>22</count>
            <item_version>0</item_version>
            <item class_id="28" tracking_level="1" version="0" object_id="_59">
              <id>10</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_60">
              <id>11</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_61">
              <id>12</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_62">
              <id>13</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_63">
              <id>14</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_64">
              <id>15</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_65">
              <id>16</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_66">
              <id>17</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_67">
              <id>18</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_68">
              <id>19</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_69">
              <id>20</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_70">
              <id>21</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_71">
              <id>22</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_72">
              <id>23</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_73">
              <id>24</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_74">
              <id>25</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_75">
              <id>26</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_76">
              <id>27</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_77">
              <id>28</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_78">
              <id>29</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_79">
              <id>30</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_80">
              <id>31</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
          </operations>
        </item>
        <item class_id_reference="26" object_id="_81">
          <id>2</id>
          <operations>
            <count>5</count>
            <item_version>0</item_version>
            <item class_id_reference="28" object_id="_82">
              <id>33</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_83">
              <id>34</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_84">
              <id>35</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_85">
              <id>36</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_86">
              <id>37</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
          </operations>
        </item>
        <item class_id_reference="26" object_id="_87">
          <id>3</id>
          <operations>
            <count>7</count>
            <item_version>0</item_version>
            <item class_id_reference="28" object_id="_88">
              <id>39</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_89">
              <id>40</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_90">
              <id>41</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_91">
              <id>42</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_92">
              <id>43</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_93">
              <id>45</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_94">
              <id>46</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
          </operations>
        </item>
      </states>
      <transitions class_id="29" tracking_level="0" version="0">
        <count>3</count>
        <item_version>0</item_version>
        <item class_id="30" tracking_level="1" version="0" object_id="_95">
          <inState>1</inState>
          <outState>2</outState>
          <condition class_id="31" tracking_level="0" version="0">
            <id>8</id>
            <sop class_id="32" tracking_level="0" version="0">
              <count>1</count>
              <item_version>0</item_version>
              <item class_id="33" tracking_level="0" version="0">
                <count>0</count>
                <item_version>0</item_version>
              </item>
            </sop>
          </condition>
        </item>
        <item class_id_reference="30" object_id="_96">
          <inState>2</inState>
          <outState>3</outState>
          <condition>
            <id>9</id>
            <sop>
              <count>1</count>
              <item_version>0</item_version>
              <item>
                <count>0</count>
                <item_version>0</item_version>
              </item>
            </sop>
          </condition>
        </item>
        <item class_id_reference="30" object_id="_97">
          <inState>3</inState>
          <outState>2</outState>
          <condition>
            <id>11</id>
            <sop>
              <count>1</count>
              <item_version>0</item_version>
              <item>
                <count>0</count>
                <item_version>0</item_version>
              </item>
            </sop>
          </condition>
        </item>
      </transitions>
    </fsm>
    <res class_id="34" tracking_level="1" version="0" object_id="_98">
      <dp_component_resource class_id="35" tracking_level="0" version="0">
        <count>0</count>
        <item_version>0</item_version>
      </dp_component_resource>
      <dp_expression_resource>
        <count>3</count>
        <item_version>0</item_version>
        <item class_id="36" tracking_level="0" version="0">
          <first>iosc_counter_clk_V_a_fu_111_p2 ( + ) </first>
          <second class_id="37" tracking_level="0" version="0">
            <count>4</count>
            <item_version>0</item_version>
            <item class_id="38" tracking_level="0" version="0">
              <first>(0P0)</first>
              <second>32</second>
            </item>
            <item>
              <first>(1P1)</first>
              <second>1</second>
            </item>
            <item>
              <first>FF</first>
              <second>101</second>
            </item>
            <item>
              <first>LUT</first>
              <second>37</second>
            </item>
          </second>
        </item>
        <item>
          <first>iosc_secCounter_V_o ( + ) </first>
          <second>
            <count>4</count>
            <item_version>0</item_version>
            <item>
              <first>(0P0)</first>
              <second>4</second>
            </item>
            <item>
              <first>(1P1)</first>
              <second>1</second>
            </item>
            <item>
              <first>FF</first>
              <second>17</second>
            </item>
            <item>
              <first>LUT</first>
              <second>9</second>
            </item>
          </second>
        </item>
        <item>
          <first>tmp_2_fu_118_p2 ( icmp ) </first>
          <second>
            <count>4</count>
            <item_version>0</item_version>
            <item>
              <first>(0P0)</first>
              <second>32</second>
            </item>
            <item>
              <first>(1P1)</first>
              <second>26</second>
            </item>
            <item>
              <first>FF</first>
              <second>0</second>
            </item>
            <item>
              <first>LUT</first>
              <second>16</second>
            </item>
          </second>
        </item>
      </dp_expression_resource>
      <dp_fifo_resource>
        <count>0</count>
        <item_version>0</item_version>
      </dp_fifo_resource>
      <dp_memory_resource>
        <count>0</count>
        <item_version>0</item_version>
      </dp_memory_resource>
      <dp_multiplexer_resource>
        <count>2</count>
        <item_version>0</item_version>
        <item>
          <first>ap_NS_fsm</first>
          <second>
            <count>4</count>
            <item_version>0</item_version>
            <item>
              <first>(0Size)</first>
              <second>3</second>
            </item>
            <item>
              <first>(1Bits)</first>
              <second>1</second>
            </item>
            <item>
              <first>(2Count)</first>
              <second>3</second>
            </item>
            <item>
              <first>LUT</first>
              <second>15</second>
            </item>
          </second>
        </item>
        <item>
          <first>iosc_counter_clk_V_o</first>
          <second>
            <count>4</count>
            <item_version>0</item_version>
            <item>
              <first>(0Size)</first>
              <second>3</second>
            </item>
            <item>
              <first>(1Bits)</first>
              <second>32</second>
            </item>
            <item>
              <first>(2Count)</first>
              <second>96</second>
            </item>
            <item>
              <first>LUT</first>
              <second>15</second>
            </item>
          </second>
        </item>
      </dp_multiplexer_resource>
      <dp_register_resource>
        <count>2</count>
        <item_version>0</item_version>
        <item>
          <first>ap_CS_fsm</first>
          <second>
            <count>3</count>
            <item_version>0</item_version>
            <item>
              <first>(Bits)</first>
              <second>3</second>
            </item>
            <item>
              <first>(Consts)</first>
              <second>0</second>
            </item>
            <item>
              <first>FF</first>
              <second>3</second>
            </item>
          </second>
        </item>
        <item>
          <first>tmp_2_reg_131</first>
          <second>
            <count>3</count>
            <item_version>0</item_version>
            <item>
              <first>(Bits)</first>
              <second>1</second>
            </item>
            <item>
              <first>(Consts)</first>
              <second>0</second>
            </item>
            <item>
              <first>FF</first>
              <second>1</second>
            </item>
          </second>
        </item>
      </dp_register_resource>
      <dp_component_map class_id="39" tracking_level="0" version="0">
        <count>0</count>
        <item_version>0</item_version>
      </dp_component_map>
      <dp_expression_map>
        <count>3</count>
        <item_version>0</item_version>
        <item class_id="40" tracking_level="0" version="0">
          <first>iosc_counter_clk_V_a_fu_111_p2 ( + ) </first>
          <second>
            <count>1</count>
            <item_version>0</item_version>
            <item>34</item>
          </second>
        </item>
        <item>
          <first>iosc_secCounter_V_o ( + ) </first>
          <second>
            <count>1</count>
            <item_version>0</item_version>
            <item>40</item>
          </second>
        </item>
        <item>
          <first>tmp_2_fu_118_p2 ( icmp ) </first>
          <second>
            <count>1</count>
            <item_version>0</item_version>
            <item>36</item>
          </second>
        </item>
      </dp_expression_map>
      <dp_fifo_map>
        <count>0</count>
        <item_version>0</item_version>
      </dp_fifo_map>
      <dp_memory_map>
        <count>0</count>
        <item_version>0</item_version>
      </dp_memory_map>
    </res>
    <node_label_latency class_id="41" tracking_level="0" version="0">
      <count>13</count>
      <item_version>0</item_version>
      <item class_id="42" tracking_level="0" version="0">
        <first>31</first>
        <second class_id="43" tracking_level="0" version="0">
          <first>0</first>
          <second>0</second>
        </second>
      </item>
      <item>
        <first>33</first>
        <second>
          <first>1</first>
          <second>0</second>
        </second>
      </item>
      <item>
        <first>34</first>
        <second>
          <first>1</first>
          <second>0</second>
        </second>
      </item>
      <item>
        <first>35</first>
        <second>
          <first>1</first>
          <second>0</second>
        </second>
      </item>
      <item>
        <first>36</first>
        <second>
          <first>1</first>
          <second>0</second>
        </second>
      </item>
      <item>
        <first>37</first>
        <second>
          <first>1</first>
          <second>0</second>
        </second>
      </item>
      <item>
        <first>39</first>
        <second>
          <first>2</first>
          <second>0</second>
        </second>
      </item>
      <item>
        <first>40</first>
        <second>
          <first>2</first>
          <second>0</second>
        </second>
      </item>
      <item>
        <first>41</first>
        <second>
          <first>2</first>
          <second>0</second>
        </second>
      </item>
      <item>
        <first>42</first>
        <second>
          <first>2</first>
          <second>0</second>
        </second>
      </item>
      <item>
        <first>43</first>
        <second>
          <first>2</first>
          <second>0</second>
        </second>
      </item>
      <item>
        <first>45</first>
        <second>
          <first>2</first>
          <second>0</second>
        </second>
      </item>
      <item>
        <first>46</first>
        <second>
          <first>2</first>
          <second>0</second>
        </second>
      </item>
    </node_label_latency>
    <bblk_ent_exit class_id="44" tracking_level="0" version="0">
      <count>4</count>
      <item_version>0</item_version>
      <item class_id="45" tracking_level="0" version="0">
        <first>32</first>
        <second class_id="46" tracking_level="0" version="0">
          <first>0</first>
          <second>0</second>
        </second>
      </item>
      <item>
        <first>38</first>
        <second>
          <first>1</first>
          <second>1</second>
        </second>
      </item>
      <item>
        <first>44</first>
        <second>
          <first>2</first>
          <second>2</second>
        </second>
      </item>
      <item>
        <first>47</first>
        <second>
          <first>2</first>
          <second>2</second>
        </second>
      </item>
    </bblk_ent_exit>
    <regions class_id="47" tracking_level="0" version="0">
      <count>1</count>
      <item_version>0</item_version>
      <item class_id="48" tracking_level="1" version="0" object_id="_99">
        <region_name>__ssdm_reset__</region_name>
        <basic_blocks>
          <count>1</count>
          <item_version>0</item_version>
          <item>32</item>
        </basic_blocks>
        <nodes>
          <count>5</count>
          <item_version>0</item_version>
          <item>26</item>
          <item>27</item>
          <item>28</item>
          <item>29</item>
          <item>30</item>
        </nodes>
        <anchor_node>26</anchor_node>
        <region_type>1</region_type>
        <interval>0</interval>
        <pipe_depth>0</pipe_depth>
      </item>
    </regions>
    <dp_fu_nodes class_id="49" tracking_level="0" version="0">
      <count>7</count>
      <item_version>0</item_version>
      <item class_id="50" tracking_level="0" version="0">
        <first>84</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>33</item>
        </second>
      </item>
      <item>
        <first>90</first>
        <second>
          <count>2</count>
          <item_version>0</item_version>
          <item>35</item>
          <item>42</item>
        </second>
      </item>
      <item>
        <first>97</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>39</item>
        </second>
      </item>
      <item>
        <first>103</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>41</item>
        </second>
      </item>
      <item>
        <first>111</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>34</item>
        </second>
      </item>
      <item>
        <first>118</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>36</item>
        </second>
      </item>
      <item>
        <first>124</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>40</item>
        </second>
      </item>
    </dp_fu_nodes>
    <dp_fu_nodes_expression class_id="52" tracking_level="0" version="0">
      <count>3</count>
      <item_version>0</item_version>
      <item class_id="53" tracking_level="0" version="0">
        <first>iosc_counter_clk_V_a_fu_111</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>34</item>
        </second>
      </item>
      <item>
        <first>tmp_2_fu_118</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>36</item>
        </second>
      </item>
      <item>
        <first>tmp_3_fu_124</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>40</item>
        </second>
      </item>
    </dp_fu_nodes_expression>
    <dp_fu_nodes_module>
      <count>0</count>
      <item_version>0</item_version>
    </dp_fu_nodes_module>
    <dp_fu_nodes_io>
      <count>4</count>
      <item_version>0</item_version>
      <item>
        <first>StgValue_33_write_fu_103</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>41</item>
        </second>
      </item>
      <item>
        <first>grp_write_fu_90</first>
        <second>
          <count>2</count>
          <item_version>0</item_version>
          <item>35</item>
          <item>42</item>
        </second>
      </item>
      <item>
        <first>iosc_counter_clk_V_r_read_fu_84</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>33</item>
        </second>
      </item>
      <item>
        <first>iosc_secCounter_V_re_read_fu_97</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>39</item>
        </second>
      </item>
    </dp_fu_nodes_io>
    <return_ports>
      <count>0</count>
      <item_version>0</item_version>
    </return_ports>
    <dp_mem_port_nodes class_id="54" tracking_level="0" version="0">
      <count>0</count>
      <item_version>0</item_version>
    </dp_mem_port_nodes>
    <dp_reg_nodes>
      <count>1</count>
      <item_version>0</item_version>
      <item>
        <first>131</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>36</item>
        </second>
      </item>
    </dp_reg_nodes>
    <dp_regname_nodes>
      <count>1</count>
      <item_version>0</item_version>
      <item>
        <first>tmp_2_reg_131</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>36</item>
        </second>
      </item>
    </dp_regname_nodes>
    <dp_reg_phi>
      <count>0</count>
      <item_version>0</item_version>
    </dp_reg_phi>
    <dp_regname_phi>
      <count>0</count>
      <item_version>0</item_version>
    </dp_regname_phi>
    <dp_port_io_nodes class_id="55" tracking_level="0" version="0">
      <count>2</count>
      <item_version>0</item_version>
      <item class_id="56" tracking_level="0" version="0">
        <first>iosc_counter_clk_V</first>
        <second>
          <count>2</count>
          <item_version>0</item_version>
          <item>
            <first>read</first>
            <second>
              <count>1</count>
              <item_version>0</item_version>
              <item>33</item>
            </second>
          </item>
          <item>
            <first>write</first>
            <second>
              <count>2</count>
              <item_version>0</item_version>
              <item>35</item>
              <item>42</item>
            </second>
          </item>
        </second>
      </item>
      <item>
        <first>iosc_secCounter_V</first>
        <second>
          <count>2</count>
          <item_version>0</item_version>
          <item>
            <first>read</first>
            <second>
              <count>1</count>
              <item_version>0</item_version>
              <item>39</item>
            </second>
          </item>
          <item>
            <first>write</first>
            <second>
              <count>1</count>
              <item_version>0</item_version>
              <item>41</item>
            </second>
          </item>
        </second>
      </item>
    </dp_port_io_nodes>
    <port2core class_id="57" tracking_level="0" version="0">
      <count>0</count>
      <item_version>0</item_version>
    </port2core>
    <node2core>
      <count>0</count>
      <item_version>0</item_version>
    </node2core>
  </syndb>
</boost_serialization>
