// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.2
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module iosc_iosThread (
        ap_clk,
        ap_rst,
        ctrl,
        inSwitch,
        outLeds,
        outLeds_ap_vld,
        iosc_switchs_V,
        iosc_switchs_V_ap_vld,
        iosc_secCounter_V
);

parameter    ap_ST_fsm_state2 = 4'd2;
parameter    ap_ST_fsm_state3 = 4'd4;
parameter    ap_ST_fsm_state4 = 4'd8;

input   ap_clk;
input   ap_rst;
input  [3:0] ctrl;
input  [3:0] inSwitch;
output  [3:0] outLeds;
output   outLeds_ap_vld;
output  [3:0] iosc_switchs_V;
output   iosc_switchs_V_ap_vld;
input  [3:0] iosc_secCounter_V;

reg outLeds_ap_vld;
reg iosc_switchs_V_ap_vld;

wire   [0:0] tmp_fu_125_p2;
reg   [0:0] tmp_reg_138;
(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_state3;
wire   [3:0] r_V_fu_131_p2;
reg   [3:0] v_V_phi_fu_117_p4;
reg   [3:0] v_V_reg_114;
wire    ap_CS_fsm_state4;
reg   [3:0] ap_NS_fsm;

// power-on initialization
initial begin
#0 ap_CS_fsm = 4'd2;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state2;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state3) & (tmp_fu_125_p2 == 1'd1))) begin
        v_V_reg_114 <= iosc_secCounter_V;
    end else if (((1'b1 == ap_CS_fsm_state4) & (tmp_reg_138 == 1'd0))) begin
        v_V_reg_114 <= r_V_fu_131_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        tmp_reg_138 <= tmp_fu_125_p2;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        iosc_switchs_V_ap_vld = 1'b1;
    end else begin
        iosc_switchs_V_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        outLeds_ap_vld = 1'b1;
    end else begin
        outLeds_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) & (tmp_reg_138 == 1'd0))) begin
        v_V_phi_fu_117_p4 = r_V_fu_131_p2;
    end else begin
        v_V_phi_fu_117_p4 = v_V_reg_114;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign iosc_switchs_V = v_V_phi_fu_117_p4;

assign outLeds = v_V_phi_fu_117_p4;

assign r_V_fu_131_p2 = (ctrl & inSwitch);

assign tmp_fu_125_p2 = ((ctrl == 4'd0) ? 1'b1 : 1'b0);

endmodule //iosc_iosThread
