// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.2
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef __linux__

#include "xstatus.h"
#include "xparameters.h"
#include "xdifferentiate.h"

extern XDifferentiate_Config XDifferentiate_ConfigTable[];

XDifferentiate_Config *XDifferentiate_LookupConfig(u16 DeviceId) {
	XDifferentiate_Config *ConfigPtr = NULL;

	int Index;

	for (Index = 0; Index < XPAR_XDIFFERENTIATE_NUM_INSTANCES; Index++) {
		if (XDifferentiate_ConfigTable[Index].DeviceId == DeviceId) {
			ConfigPtr = &XDifferentiate_ConfigTable[Index];
			break;
		}
	}

	return ConfigPtr;
}

int XDifferentiate_Initialize(XDifferentiate *InstancePtr, u16 DeviceId) {
	XDifferentiate_Config *ConfigPtr;

	Xil_AssertNonvoid(InstancePtr != NULL);

	ConfigPtr = XDifferentiate_LookupConfig(DeviceId);
	if (ConfigPtr == NULL) {
		InstancePtr->IsReady = 0;
		return (XST_DEVICE_NOT_FOUND);
	}

	return XDifferentiate_CfgInitialize(InstancePtr, ConfigPtr);
}

#endif

