// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.2
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "differentiate.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic differentiate::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic differentiate::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<19> differentiate::ap_ST_fsm_state1 = "1";
const sc_lv<19> differentiate::ap_ST_fsm_state2 = "10";
const sc_lv<19> differentiate::ap_ST_fsm_state3 = "100";
const sc_lv<19> differentiate::ap_ST_fsm_state4 = "1000";
const sc_lv<19> differentiate::ap_ST_fsm_state5 = "10000";
const sc_lv<19> differentiate::ap_ST_fsm_state6 = "100000";
const sc_lv<19> differentiate::ap_ST_fsm_state7 = "1000000";
const sc_lv<19> differentiate::ap_ST_fsm_state8 = "10000000";
const sc_lv<19> differentiate::ap_ST_fsm_state9 = "100000000";
const sc_lv<19> differentiate::ap_ST_fsm_state10 = "1000000000";
const sc_lv<19> differentiate::ap_ST_fsm_state11 = "10000000000";
const sc_lv<19> differentiate::ap_ST_fsm_state12 = "100000000000";
const sc_lv<19> differentiate::ap_ST_fsm_state13 = "1000000000000";
const sc_lv<19> differentiate::ap_ST_fsm_state14 = "10000000000000";
const sc_lv<19> differentiate::ap_ST_fsm_state15 = "100000000000000";
const sc_lv<19> differentiate::ap_ST_fsm_state16 = "1000000000000000";
const sc_lv<19> differentiate::ap_ST_fsm_state17 = "10000000000000000";
const sc_lv<19> differentiate::ap_ST_fsm_state18 = "100000000000000000";
const sc_lv<19> differentiate::ap_ST_fsm_state19 = "1000000000000000000";
const sc_lv<32> differentiate::ap_const_lv32_0 = "00000000000000000000000000000000";
const int differentiate::C_S_AXI_DATA_WIDTH = "100000";
const sc_lv<32> differentiate::ap_const_lv32_5 = "101";
const sc_lv<32> differentiate::ap_const_lv32_7 = "111";
const sc_lv<32> differentiate::ap_const_lv32_6 = "110";
const sc_lv<32> differentiate::ap_const_lv32_8 = "1000";
const sc_lv<32> differentiate::ap_const_lv32_9 = "1001";
const sc_lv<32> differentiate::ap_const_lv32_D = "1101";
const sc_lv<32> differentiate::ap_const_lv32_A = "1010";
const sc_lv<32> differentiate::ap_const_lv32_C = "1100";
const sc_lv<32> differentiate::ap_const_lv32_B = "1011";
const sc_lv<32> differentiate::ap_const_lv32_1 = "1";
const sc_lv<1> differentiate::ap_const_lv1_0 = "0";
const sc_lv<32> differentiate::ap_const_lv32_2 = "10";
const sc_lv<32> differentiate::ap_const_lv32_3 = "11";
const sc_lv<32> differentiate::ap_const_lv32_4 = "100";
const sc_lv<32> differentiate::ap_const_lv32_E = "1110";
const sc_lv<32> differentiate::ap_const_lv32_F = "1111";
const sc_lv<32> differentiate::ap_const_lv32_10 = "10000";
const sc_lv<32> differentiate::ap_const_lv32_11 = "10001";
const sc_lv<6> differentiate::ap_const_lv6_1 = "1";
const sc_lv<1> differentiate::ap_const_lv1_1 = "1";
const sc_lv<32> differentiate::ap_const_lv32_12 = "10010";
const sc_lv<6> differentiate::ap_const_lv6_0 = "000000";
const sc_lv<4> differentiate::ap_const_lv4_0 = "0000";
const sc_lv<6> differentiate::ap_const_lv6_3F = "111111";
const sc_lv<12> differentiate::ap_const_lv12_2E = "101110";
const sc_lv<6> differentiate::ap_const_lv6_2F = "101111";
const sc_lv<15> differentiate::ap_const_lv15_0 = "000000000000000";
const bool differentiate::ap_const_boolean_1 = true;

differentiate::differentiate(sc_module_name name) : sc_module(name), mVcdFile(0) {
    differentiate_diff_io_s_axi_U = new differentiate_diff_io_s_axi<C_S_AXI_DIFF_IO_ADDR_WIDTH,C_S_AXI_DIFF_IO_DATA_WIDTH>("differentiate_diff_io_s_axi_U");
    differentiate_diff_io_s_axi_U->AWVALID(s_axi_diff_io_AWVALID);
    differentiate_diff_io_s_axi_U->AWREADY(s_axi_diff_io_AWREADY);
    differentiate_diff_io_s_axi_U->AWADDR(s_axi_diff_io_AWADDR);
    differentiate_diff_io_s_axi_U->WVALID(s_axi_diff_io_WVALID);
    differentiate_diff_io_s_axi_U->WREADY(s_axi_diff_io_WREADY);
    differentiate_diff_io_s_axi_U->WDATA(s_axi_diff_io_WDATA);
    differentiate_diff_io_s_axi_U->WSTRB(s_axi_diff_io_WSTRB);
    differentiate_diff_io_s_axi_U->ARVALID(s_axi_diff_io_ARVALID);
    differentiate_diff_io_s_axi_U->ARREADY(s_axi_diff_io_ARREADY);
    differentiate_diff_io_s_axi_U->ARADDR(s_axi_diff_io_ARADDR);
    differentiate_diff_io_s_axi_U->RVALID(s_axi_diff_io_RVALID);
    differentiate_diff_io_s_axi_U->RREADY(s_axi_diff_io_RREADY);
    differentiate_diff_io_s_axi_U->RDATA(s_axi_diff_io_RDATA);
    differentiate_diff_io_s_axi_U->RRESP(s_axi_diff_io_RRESP);
    differentiate_diff_io_s_axi_U->BVALID(s_axi_diff_io_BVALID);
    differentiate_diff_io_s_axi_U->BREADY(s_axi_diff_io_BREADY);
    differentiate_diff_io_s_axi_U->BRESP(s_axi_diff_io_BRESP);
    differentiate_diff_io_s_axi_U->ACLK(ap_clk);
    differentiate_diff_io_s_axi_U->ARESET(ap_rst_n_inv);
    differentiate_diff_io_s_axi_U->ACLK_EN(ap_var_for_const0);
    differentiate_diff_io_s_axi_U->ap_start(ap_start);
    differentiate_diff_io_s_axi_U->interrupt(interrupt);
    differentiate_diff_io_s_axi_U->ap_ready(ap_ready);
    differentiate_diff_io_s_axi_U->ap_done(ap_done);
    differentiate_diff_io_s_axi_U->ap_idle(ap_idle);
    differentiate_diff_io_s_axi_U->img_address0(img_address0);
    differentiate_diff_io_s_axi_U->img_ce0(img_ce0);
    differentiate_diff_io_s_axi_U->img_q0(img_q0);
    differentiate_diff_io_s_axi_U->window_V_address0(window_V_address0);
    differentiate_diff_io_s_axi_U->window_V_ce0(window_V_ce0);
    differentiate_diff_io_s_axi_U->window_V_q0(window_V_q0);
    differentiate_mulbkb_U0 = new differentiate_mulbkb<1,2,6,7,12>("differentiate_mulbkb_U0");
    differentiate_mulbkb_U0->clk(ap_clk);
    differentiate_mulbkb_U0->reset(ap_rst_n_inv);
    differentiate_mulbkb_U0->din0(grp_fu_340_p0);
    differentiate_mulbkb_U0->din1(grp_fu_340_p1);
    differentiate_mulbkb_U0->ce(ap_var_for_const0);
    differentiate_mulbkb_U0->dout(grp_fu_340_p2);
    differentiate_maccud_U1 = new differentiate_maccud<1,1,3,8,11,12>("differentiate_maccud_U1");
    differentiate_maccud_U1->din0(reg_275);
    differentiate_maccud_U1->din1(grp_fu_813_p1);
    differentiate_maccud_U1->din2(r_V_reg_966);
    differentiate_maccud_U1->dout(grp_fu_813_p3);
    differentiate_maccud_U2 = new differentiate_maccud<1,1,3,8,11,12>("differentiate_maccud_U2");
    differentiate_maccud_U2->din0(reg_279);
    differentiate_maccud_U2->din1(grp_fu_821_p1);
    differentiate_maccud_U2->din2(r_V_1_2_reg_1028);
    differentiate_maccud_U2->dout(grp_fu_821_p3);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state10);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state11);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state12);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state13);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state14);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state15);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state16);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state17);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state18);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state19);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state5);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state6);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state7);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state8);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state9);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( exitcond1_fu_325_p2 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( exitcond1_fu_325_p2 );

    SC_METHOD(thread_ap_rst_n_inv);
    sensitive << ( ap_rst_n );

    SC_METHOD(thread_exitcond1_fu_325_p2);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( i_reg_243 );

    SC_METHOD(thread_exitcond2_fu_444_p2);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( j_reg_255 );

    SC_METHOD(thread_grp_fu_340_p0);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( grp_fu_340_p00 );

    SC_METHOD(thread_grp_fu_340_p00);
    sensitive << ( tmp_reg_884 );

    SC_METHOD(thread_grp_fu_340_p1);
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_grp_fu_813_p1);
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( grp_fu_813_p10 );

    SC_METHOD(thread_grp_fu_813_p10);
    sensitive << ( reg_271 );

    SC_METHOD(thread_grp_fu_821_p1);
    sensitive << ( ap_CS_fsm_state14 );
    sensitive << ( grp_fu_821_p10 );

    SC_METHOD(thread_grp_fu_821_p10);
    sensitive << ( reg_283 );

    SC_METHOD(thread_i_1_fu_374_p2);
    sensitive << ( i_reg_243 );

    SC_METHOD(thread_img_address0);
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( ap_CS_fsm_state14 );
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( ap_CS_fsm_state13 );
    sensitive << ( ap_CS_fsm_state12 );
    sensitive << ( img_addr_1_reg_920 );
    sensitive << ( img_addr_4_reg_925 );
    sensitive << ( img_addr_7_reg_930 );
    sensitive << ( tmp_19_cast_fu_467_p1 );
    sensitive << ( tmp_23_cast_fu_505_p1 );
    sensitive << ( tmp_20_cast_fu_514_p1 );
    sensitive << ( tmp_24_cast_fu_542_p1 );
    sensitive << ( tmp_21_cast_fu_546_p1 );
    sensitive << ( tmp_25_cast_fu_564_p1 );

    SC_METHOD(thread_img_ce0);
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( ap_CS_fsm_state14 );
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( ap_CS_fsm_state13 );
    sensitive << ( ap_CS_fsm_state12 );

    SC_METHOD(thread_j_1_cast_cast_fu_497_p1);
    sensitive << ( j_1_reg_960 );

    SC_METHOD(thread_j_1_fu_477_p2);
    sensitive << ( j_reg_255 );

    SC_METHOD(thread_j_cast_cast_fu_410_p1);
    sensitive << ( j_reg_255 );

    SC_METHOD(thread_p_shl1_cast_fu_315_p1);
    sensitive << ( tmp_7_fu_307_p3 );

    SC_METHOD(thread_p_shl2_cast_fu_388_p1);
    sensitive << ( tmp_12_fu_380_p3 );

    SC_METHOD(thread_p_shl3_cast_fu_400_p1);
    sensitive << ( tmp_13_fu_392_p3 );

    SC_METHOD(thread_p_shl4_cast_fu_353_p1);
    sensitive << ( tmp_9_fu_346_p3 );

    SC_METHOD(thread_p_shl5_cast_fu_364_p1);
    sensitive << ( tmp_3_fu_357_p3 );

    SC_METHOD(thread_p_shl_cast_fu_303_p1);
    sensitive << ( tmp_6_fu_295_p3 );

    SC_METHOD(thread_r_V_0_2_fu_587_p0);
    sensitive << ( reg_267 );
    sensitive << ( ap_CS_fsm_state16 );

    SC_METHOD(thread_r_V_0_2_fu_587_p1);
    sensitive << ( ap_CS_fsm_state16 );
    sensitive << ( r_V_0_2_fu_587_p10 );

    SC_METHOD(thread_r_V_0_2_fu_587_p10);
    sensitive << ( reg_271 );

    SC_METHOD(thread_r_V_0_2_fu_587_p2);
    sensitive << ( r_V_0_2_fu_587_p0 );
    sensitive << ( r_V_0_2_fu_587_p1 );

    SC_METHOD(thread_r_V_1_2_fu_558_p0);
    sensitive << ( reg_287 );
    sensitive << ( ap_CS_fsm_state13 );

    SC_METHOD(thread_r_V_1_2_fu_558_p1);
    sensitive << ( ap_CS_fsm_state13 );
    sensitive << ( r_V_1_2_fu_558_p10 );

    SC_METHOD(thread_r_V_1_2_fu_558_p10);
    sensitive << ( reg_291 );

    SC_METHOD(thread_r_V_1_2_fu_558_p2);
    sensitive << ( r_V_1_2_fu_558_p0 );
    sensitive << ( r_V_1_2_fu_558_p1 );

    SC_METHOD(thread_r_V_1_fu_600_p0);
    sensitive << ( reg_275 );
    sensitive << ( ap_CS_fsm_state16 );

    SC_METHOD(thread_r_V_1_fu_600_p1);
    sensitive << ( ap_CS_fsm_state16 );
    sensitive << ( r_V_1_fu_600_p10 );

    SC_METHOD(thread_r_V_1_fu_600_p10);
    sensitive << ( img_load_3_reg_1008 );

    SC_METHOD(thread_r_V_1_fu_600_p2);
    sensitive << ( r_V_1_fu_600_p0 );
    sensitive << ( r_V_1_fu_600_p1 );

    SC_METHOD(thread_r_V_2_1_fu_627_p0);
    sensitive << ( reg_287 );
    sensitive << ( ap_CS_fsm_state16 );

    SC_METHOD(thread_r_V_2_1_fu_627_p1);
    sensitive << ( ap_CS_fsm_state16 );
    sensitive << ( r_V_2_1_fu_627_p10 );

    SC_METHOD(thread_r_V_2_1_fu_627_p10);
    sensitive << ( reg_283 );

    SC_METHOD(thread_r_V_2_1_fu_627_p2);
    sensitive << ( r_V_2_1_fu_627_p0 );
    sensitive << ( r_V_2_1_fu_627_p1 );

    SC_METHOD(thread_r_V_2_2_fu_640_p0);
    sensitive << ( reg_279 );
    sensitive << ( ap_CS_fsm_state16 );

    SC_METHOD(thread_r_V_2_2_fu_640_p1);
    sensitive << ( ap_CS_fsm_state16 );
    sensitive << ( r_V_2_2_fu_640_p10 );

    SC_METHOD(thread_r_V_2_2_fu_640_p10);
    sensitive << ( img_load_8_reg_1044 );

    SC_METHOD(thread_r_V_2_2_fu_640_p2);
    sensitive << ( r_V_2_2_fu_640_p0 );
    sensitive << ( r_V_2_2_fu_640_p1 );

    SC_METHOD(thread_r_V_2_fu_613_p0);
    sensitive << ( window_V_load_6_reg_1023 );
    sensitive << ( ap_CS_fsm_state16 );

    SC_METHOD(thread_r_V_2_fu_613_p1);
    sensitive << ( ap_CS_fsm_state16 );
    sensitive << ( r_V_2_fu_613_p10 );

    SC_METHOD(thread_r_V_2_fu_613_p10);
    sensitive << ( reg_291 );

    SC_METHOD(thread_r_V_2_fu_613_p2);
    sensitive << ( r_V_2_fu_613_p0 );
    sensitive << ( r_V_2_fu_613_p1 );

    SC_METHOD(thread_r_V_fu_491_p0);
    sensitive << ( reg_267 );
    sensitive << ( ap_CS_fsm_state8 );

    SC_METHOD(thread_r_V_fu_491_p1);
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( r_V_fu_491_p10 );

    SC_METHOD(thread_r_V_fu_491_p10);
    sensitive << ( reg_271 );

    SC_METHOD(thread_r_V_fu_491_p2);
    sensitive << ( r_V_fu_491_p0 );
    sensitive << ( r_V_fu_491_p1 );

    SC_METHOD(thread_res_V_address0);
    sensitive << ( ap_CS_fsm_state19 );
    sensitive << ( tmp_22_cast_fu_809_p1 );

    SC_METHOD(thread_res_V_ce0);
    sensitive << ( ap_CS_fsm_state19 );

    SC_METHOD(thread_res_V_d0);
    sensitive << ( tmp_5_reg_1096 );
    sensitive << ( ap_CS_fsm_state19 );

    SC_METHOD(thread_res_V_we0);
    sensitive << ( ap_CS_fsm_state19 );

    SC_METHOD(thread_temp_result_V_1_2_2_fu_769_p2);
    sensitive << ( tmp7_cast_fu_763_p1 );
    sensitive << ( tmp10_cast_fu_766_p1 );

    SC_METHOD(thread_tmp10_cast_fu_766_p1);
    sensitive << ( tmp4_reg_1081 );

    SC_METHOD(thread_tmp10_fu_728_p2);
    sensitive << ( tmp15_cast_fu_721_p1 );
    sensitive << ( tmp16_cast_fu_725_p1 );

    SC_METHOD(thread_tmp11_cast_fu_686_p1);
    sensitive << ( tmp1_reg_1038 );

    SC_METHOD(thread_tmp12_cast_fu_705_p1);
    sensitive << ( tmp3_fu_699_p2 );

    SC_METHOD(thread_tmp12_fu_737_p2);
    sensitive << ( tmp_0_2_cast_fu_646_p1 );
    sensitive << ( tmp_2_2_cast_fu_664_p1 );

    SC_METHOD(thread_tmp13_cast_fu_695_p1);
    sensitive << ( tmp2_fu_689_p2 );

    SC_METHOD(thread_tmp13_fu_747_p2);
    sensitive << ( tmp_8_cast_fu_652_p1 );
    sensitive << ( tmp20_cast_fu_743_p1 );

    SC_METHOD(thread_tmp14_cast_fu_783_p1);
    sensitive << ( tmp10_reg_1086 );

    SC_METHOD(thread_tmp14_fu_757_p2);
    sensitive << ( tmp18_cast_fu_734_p1 );
    sensitive << ( tmp19_cast_fu_753_p1 );

    SC_METHOD(thread_tmp15_cast_fu_721_p1);
    sensitive << ( tmp5_fu_715_p2 );

    SC_METHOD(thread_tmp16_cast_fu_725_p1);
    sensitive << ( tmp1_reg_1038 );

    SC_METHOD(thread_tmp17_cast_fu_786_p1);
    sensitive << ( tmp14_reg_1091 );

    SC_METHOD(thread_tmp18_cast_fu_734_p1);
    sensitive << ( tmp8_reg_1002 );

    SC_METHOD(thread_tmp19_cast_fu_753_p1);
    sensitive << ( tmp13_fu_747_p2 );

    SC_METHOD(thread_tmp20_cast_fu_743_p1);
    sensitive << ( tmp12_fu_737_p2 );

    SC_METHOD(thread_tmp2_fu_689_p2);
    sensitive << ( tmp_2_2_cast_fu_664_p1 );
    sensitive << ( tmp_2_1_cast_fu_661_p1 );

    SC_METHOD(thread_tmp3_fu_699_p2);
    sensitive << ( tmp_2_cast_fu_655_p1 );
    sensitive << ( tmp13_cast_fu_695_p1 );

    SC_METHOD(thread_tmp4_fu_709_p2);
    sensitive << ( tmp11_cast_fu_686_p1 );
    sensitive << ( tmp12_cast_fu_705_p1 );

    SC_METHOD(thread_tmp5_fu_715_p2);
    sensitive << ( tmp_2_1_cast_fu_661_p1 );
    sensitive << ( tmp_15_cast_fu_658_p1 );

    SC_METHOD(thread_tmp7_cast_fu_763_p1);
    sensitive << ( tmp7_reg_1076 );

    SC_METHOD(thread_tmp7_fu_680_p2);
    sensitive << ( tmp8_cast_fu_667_p1 );
    sensitive << ( tmp9_cast_fu_676_p1 );

    SC_METHOD(thread_tmp8_cast_fu_667_p1);
    sensitive << ( tmp8_reg_1002 );

    SC_METHOD(thread_tmp9_cast_fu_676_p1);
    sensitive << ( tmp9_fu_670_p2 );

    SC_METHOD(thread_tmp9_fu_670_p2);
    sensitive << ( tmp_1_cast_fu_649_p1 );
    sensitive << ( tmp_0_2_cast_fu_646_p1 );

    SC_METHOD(thread_tmp_0_2_cast_fu_646_p1);
    sensitive << ( r_V_0_2_reg_1049 );

    SC_METHOD(thread_tmp_10_fu_368_p2);
    sensitive << ( p_shl4_cast_fu_353_p1 );
    sensitive << ( p_shl5_cast_fu_364_p1 );

    SC_METHOD(thread_tmp_12_fu_380_p3);
    sensitive << ( i_1_fu_374_p2 );

    SC_METHOD(thread_tmp_13_fu_392_p3);
    sensitive << ( i_1_fu_374_p2 );

    SC_METHOD(thread_tmp_14_fu_404_p2);
    sensitive << ( p_shl2_cast_fu_388_p1 );
    sensitive << ( p_shl3_cast_fu_400_p1 );

    SC_METHOD(thread_tmp_15_cast_fu_658_p1);
    sensitive << ( r_V_2_reg_1060 );

    SC_METHOD(thread_tmp_15_fu_414_p2);
    sensitive << ( tmp_10_reg_896 );
    sensitive << ( j_cast_cast_fu_410_p1 );

    SC_METHOD(thread_tmp_16_cast_fu_419_p1);
    sensitive << ( tmp_15_fu_414_p2 );

    SC_METHOD(thread_tmp_16_fu_424_p2);
    sensitive << ( tmp_8_reg_874 );
    sensitive << ( j_cast_cast_fu_410_p1 );

    SC_METHOD(thread_tmp_17_cast_fu_429_p1);
    sensitive << ( tmp_16_fu_424_p2 );

    SC_METHOD(thread_tmp_17_fu_434_p2);
    sensitive << ( tmp_14_reg_913 );
    sensitive << ( j_cast_cast_fu_410_p1 );

    SC_METHOD(thread_tmp_18_cast_fu_439_p1);
    sensitive << ( tmp_17_fu_434_p2 );

    SC_METHOD(thread_tmp_18_fu_462_p2);
    sensitive << ( tmp_10_reg_896 );
    sensitive << ( tmp_2_cast_cast_fu_459_p1 );

    SC_METHOD(thread_tmp_19_cast_fu_467_p1);
    sensitive << ( tmp_18_fu_462_p2 );

    SC_METHOD(thread_tmp_19_fu_510_p2);
    sensitive << ( tmp_8_reg_874 );
    sensitive << ( tmp_2_cast_cast_reg_944 );

    SC_METHOD(thread_tmp_1_cast_fu_649_p1);
    sensitive << ( r_V_1_reg_1054 );

    SC_METHOD(thread_tmp_20_cast_fu_514_p1);
    sensitive << ( tmp_19_fu_510_p2 );

    SC_METHOD(thread_tmp_20_fu_519_p2);
    sensitive << ( tmp_14_reg_913 );
    sensitive << ( tmp_2_cast_cast_reg_944 );

    SC_METHOD(thread_tmp_21_cast_fu_546_p1);
    sensitive << ( tmp_20_reg_987 );

    SC_METHOD(thread_tmp_21_fu_472_p2);
    sensitive << ( tmp_11_reg_903 );
    sensitive << ( tmp_2_cast_cast6_fu_456_p1 );

    SC_METHOD(thread_tmp_22_cast_fu_809_p1);
    sensitive << ( tmp_21_reg_955 );

    SC_METHOD(thread_tmp_22_fu_500_p2);
    sensitive << ( tmp_10_reg_896 );
    sensitive << ( j_1_cast_cast_fu_497_p1 );

    SC_METHOD(thread_tmp_23_cast_fu_505_p1);
    sensitive << ( tmp_22_fu_500_p2 );

    SC_METHOD(thread_tmp_23_fu_534_p2);
    sensitive << ( tmp_8_reg_874 );
    sensitive << ( j_1_cast_cast_reg_971 );

    SC_METHOD(thread_tmp_24_cast_fu_542_p1);
    sensitive << ( tmp_23_reg_992 );

    SC_METHOD(thread_tmp_24_fu_538_p2);
    sensitive << ( tmp_14_reg_913 );
    sensitive << ( j_1_cast_cast_reg_971 );

    SC_METHOD(thread_tmp_25_cast_fu_564_p1);
    sensitive << ( tmp_24_reg_997 );

    SC_METHOD(thread_tmp_25_fu_775_p3);
    sensitive << ( temp_result_V_1_2_2_fu_769_p2 );

    SC_METHOD(thread_tmp_2_1_cast_fu_661_p1);
    sensitive << ( r_V_2_1_reg_1066 );

    SC_METHOD(thread_tmp_2_2_cast_fu_664_p1);
    sensitive << ( r_V_2_2_reg_1071 );

    SC_METHOD(thread_tmp_2_cast_cast6_fu_456_p1);
    sensitive << ( tmp_2_reg_938 );

    SC_METHOD(thread_tmp_2_cast_cast_fu_459_p1);
    sensitive << ( tmp_2_reg_938 );

    SC_METHOD(thread_tmp_2_cast_fu_655_p1);
    sensitive << ( r_V_2_reg_1060 );

    SC_METHOD(thread_tmp_2_fu_450_p2);
    sensitive << ( j_reg_255 );

    SC_METHOD(thread_tmp_3_fu_357_p3);
    sensitive << ( tmp_reg_884 );

    SC_METHOD(thread_tmp_4_fu_795_p2);
    sensitive << ( tmp_s_fu_789_p2 );

    SC_METHOD(thread_tmp_5_fu_801_p3);
    sensitive << ( tmp_s_fu_789_p2 );
    sensitive << ( tmp_25_fu_775_p3 );
    sensitive << ( tmp_4_fu_795_p2 );

    SC_METHOD(thread_tmp_6_fu_295_p3);
    sensitive << ( i_reg_243 );

    SC_METHOD(thread_tmp_7_fu_307_p3);
    sensitive << ( i_reg_243 );

    SC_METHOD(thread_tmp_8_cast_fu_652_p1);
    sensitive << ( r_V_1_reg_1054 );

    SC_METHOD(thread_tmp_8_fu_319_p2);
    sensitive << ( p_shl_cast_fu_303_p1 );
    sensitive << ( p_shl1_cast_fu_315_p1 );

    SC_METHOD(thread_tmp_9_fu_346_p3);
    sensitive << ( tmp_reg_884 );

    SC_METHOD(thread_tmp_fu_331_p2);
    sensitive << ( i_reg_243 );

    SC_METHOD(thread_tmp_s_fu_789_p2);
    sensitive << ( tmp14_cast_fu_783_p1 );
    sensitive << ( tmp17_cast_fu_786_p1 );

    SC_METHOD(thread_window_V_address0);
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( ap_CS_fsm_state13 );
    sensitive << ( ap_CS_fsm_state12 );
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_window_V_ce0);
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( ap_CS_fsm_state13 );
    sensitive << ( ap_CS_fsm_state12 );
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( exitcond1_fu_325_p2 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( exitcond2_fu_444_p2 );

    SC_THREAD(thread_hdltv_gen);
    sensitive << ( ap_clk.pos() );

    SC_THREAD(thread_ap_var_for_const0);

    ap_CS_fsm = "0000000000000000001";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "differentiate_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst_n, "(port)ap_rst_n");
    sc_trace(mVcdFile, res_V_address0, "(port)res_V_address0");
    sc_trace(mVcdFile, res_V_ce0, "(port)res_V_ce0");
    sc_trace(mVcdFile, res_V_we0, "(port)res_V_we0");
    sc_trace(mVcdFile, res_V_d0, "(port)res_V_d0");
    sc_trace(mVcdFile, s_axi_diff_io_AWVALID, "(port)s_axi_diff_io_AWVALID");
    sc_trace(mVcdFile, s_axi_diff_io_AWREADY, "(port)s_axi_diff_io_AWREADY");
    sc_trace(mVcdFile, s_axi_diff_io_AWADDR, "(port)s_axi_diff_io_AWADDR");
    sc_trace(mVcdFile, s_axi_diff_io_WVALID, "(port)s_axi_diff_io_WVALID");
    sc_trace(mVcdFile, s_axi_diff_io_WREADY, "(port)s_axi_diff_io_WREADY");
    sc_trace(mVcdFile, s_axi_diff_io_WDATA, "(port)s_axi_diff_io_WDATA");
    sc_trace(mVcdFile, s_axi_diff_io_WSTRB, "(port)s_axi_diff_io_WSTRB");
    sc_trace(mVcdFile, s_axi_diff_io_ARVALID, "(port)s_axi_diff_io_ARVALID");
    sc_trace(mVcdFile, s_axi_diff_io_ARREADY, "(port)s_axi_diff_io_ARREADY");
    sc_trace(mVcdFile, s_axi_diff_io_ARADDR, "(port)s_axi_diff_io_ARADDR");
    sc_trace(mVcdFile, s_axi_diff_io_RVALID, "(port)s_axi_diff_io_RVALID");
    sc_trace(mVcdFile, s_axi_diff_io_RREADY, "(port)s_axi_diff_io_RREADY");
    sc_trace(mVcdFile, s_axi_diff_io_RDATA, "(port)s_axi_diff_io_RDATA");
    sc_trace(mVcdFile, s_axi_diff_io_RRESP, "(port)s_axi_diff_io_RRESP");
    sc_trace(mVcdFile, s_axi_diff_io_BVALID, "(port)s_axi_diff_io_BVALID");
    sc_trace(mVcdFile, s_axi_diff_io_BREADY, "(port)s_axi_diff_io_BREADY");
    sc_trace(mVcdFile, s_axi_diff_io_BRESP, "(port)s_axi_diff_io_BRESP");
    sc_trace(mVcdFile, interrupt, "(port)interrupt");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_rst_n_inv, "ap_rst_n_inv");
    sc_trace(mVcdFile, ap_start, "ap_start");
    sc_trace(mVcdFile, ap_done, "ap_done");
    sc_trace(mVcdFile, ap_idle, "ap_idle");
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, ap_ready, "ap_ready");
    sc_trace(mVcdFile, img_address0, "img_address0");
    sc_trace(mVcdFile, img_ce0, "img_ce0");
    sc_trace(mVcdFile, img_q0, "img_q0");
    sc_trace(mVcdFile, window_V_address0, "window_V_address0");
    sc_trace(mVcdFile, window_V_ce0, "window_V_ce0");
    sc_trace(mVcdFile, window_V_q0, "window_V_q0");
    sc_trace(mVcdFile, reg_267, "reg_267");
    sc_trace(mVcdFile, ap_CS_fsm_state6, "ap_CS_fsm_state6");
    sc_trace(mVcdFile, ap_CS_fsm_state8, "ap_CS_fsm_state8");
    sc_trace(mVcdFile, reg_271, "reg_271");
    sc_trace(mVcdFile, ap_CS_fsm_state7, "ap_CS_fsm_state7");
    sc_trace(mVcdFile, ap_CS_fsm_state9, "ap_CS_fsm_state9");
    sc_trace(mVcdFile, reg_275, "reg_275");
    sc_trace(mVcdFile, reg_279, "reg_279");
    sc_trace(mVcdFile, ap_CS_fsm_state10, "ap_CS_fsm_state10");
    sc_trace(mVcdFile, ap_CS_fsm_state14, "ap_CS_fsm_state14");
    sc_trace(mVcdFile, reg_283, "reg_283");
    sc_trace(mVcdFile, ap_CS_fsm_state11, "ap_CS_fsm_state11");
    sc_trace(mVcdFile, reg_287, "reg_287");
    sc_trace(mVcdFile, ap_CS_fsm_state13, "ap_CS_fsm_state13");
    sc_trace(mVcdFile, reg_291, "reg_291");
    sc_trace(mVcdFile, ap_CS_fsm_state12, "ap_CS_fsm_state12");
    sc_trace(mVcdFile, tmp_8_fu_319_p2, "tmp_8_fu_319_p2");
    sc_trace(mVcdFile, tmp_8_reg_874, "tmp_8_reg_874");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, tmp_fu_331_p2, "tmp_fu_331_p2");
    sc_trace(mVcdFile, tmp_reg_884, "tmp_reg_884");
    sc_trace(mVcdFile, exitcond1_fu_325_p2, "exitcond1_fu_325_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, tmp_10_fu_368_p2, "tmp_10_fu_368_p2");
    sc_trace(mVcdFile, tmp_10_reg_896, "tmp_10_reg_896");
    sc_trace(mVcdFile, ap_CS_fsm_state4, "ap_CS_fsm_state4");
    sc_trace(mVcdFile, grp_fu_340_p2, "grp_fu_340_p2");
    sc_trace(mVcdFile, tmp_11_reg_903, "tmp_11_reg_903");
    sc_trace(mVcdFile, i_1_fu_374_p2, "i_1_fu_374_p2");
    sc_trace(mVcdFile, i_1_reg_908, "i_1_reg_908");
    sc_trace(mVcdFile, tmp_14_fu_404_p2, "tmp_14_fu_404_p2");
    sc_trace(mVcdFile, tmp_14_reg_913, "tmp_14_reg_913");
    sc_trace(mVcdFile, img_addr_1_reg_920, "img_addr_1_reg_920");
    sc_trace(mVcdFile, ap_CS_fsm_state5, "ap_CS_fsm_state5");
    sc_trace(mVcdFile, img_addr_4_reg_925, "img_addr_4_reg_925");
    sc_trace(mVcdFile, img_addr_7_reg_930, "img_addr_7_reg_930");
    sc_trace(mVcdFile, tmp_2_fu_450_p2, "tmp_2_fu_450_p2");
    sc_trace(mVcdFile, tmp_2_reg_938, "tmp_2_reg_938");
    sc_trace(mVcdFile, exitcond2_fu_444_p2, "exitcond2_fu_444_p2");
    sc_trace(mVcdFile, tmp_2_cast_cast_fu_459_p1, "tmp_2_cast_cast_fu_459_p1");
    sc_trace(mVcdFile, tmp_2_cast_cast_reg_944, "tmp_2_cast_cast_reg_944");
    sc_trace(mVcdFile, tmp_21_fu_472_p2, "tmp_21_fu_472_p2");
    sc_trace(mVcdFile, tmp_21_reg_955, "tmp_21_reg_955");
    sc_trace(mVcdFile, j_1_fu_477_p2, "j_1_fu_477_p2");
    sc_trace(mVcdFile, j_1_reg_960, "j_1_reg_960");
    sc_trace(mVcdFile, r_V_fu_491_p2, "r_V_fu_491_p2");
    sc_trace(mVcdFile, r_V_reg_966, "r_V_reg_966");
    sc_trace(mVcdFile, j_1_cast_cast_fu_497_p1, "j_1_cast_cast_fu_497_p1");
    sc_trace(mVcdFile, j_1_cast_cast_reg_971, "j_1_cast_cast_reg_971");
    sc_trace(mVcdFile, tmp_20_fu_519_p2, "tmp_20_fu_519_p2");
    sc_trace(mVcdFile, tmp_20_reg_987, "tmp_20_reg_987");
    sc_trace(mVcdFile, tmp_23_fu_534_p2, "tmp_23_fu_534_p2");
    sc_trace(mVcdFile, tmp_23_reg_992, "tmp_23_reg_992");
    sc_trace(mVcdFile, tmp_24_fu_538_p2, "tmp_24_fu_538_p2");
    sc_trace(mVcdFile, tmp_24_reg_997, "tmp_24_reg_997");
    sc_trace(mVcdFile, grp_fu_813_p3, "grp_fu_813_p3");
    sc_trace(mVcdFile, tmp8_reg_1002, "tmp8_reg_1002");
    sc_trace(mVcdFile, img_load_3_reg_1008, "img_load_3_reg_1008");
    sc_trace(mVcdFile, window_V_load_6_reg_1023, "window_V_load_6_reg_1023");
    sc_trace(mVcdFile, r_V_1_2_fu_558_p2, "r_V_1_2_fu_558_p2");
    sc_trace(mVcdFile, r_V_1_2_reg_1028, "r_V_1_2_reg_1028");
    sc_trace(mVcdFile, grp_fu_821_p3, "grp_fu_821_p3");
    sc_trace(mVcdFile, tmp1_reg_1038, "tmp1_reg_1038");
    sc_trace(mVcdFile, img_load_8_reg_1044, "img_load_8_reg_1044");
    sc_trace(mVcdFile, ap_CS_fsm_state15, "ap_CS_fsm_state15");
    sc_trace(mVcdFile, r_V_0_2_fu_587_p2, "r_V_0_2_fu_587_p2");
    sc_trace(mVcdFile, r_V_0_2_reg_1049, "r_V_0_2_reg_1049");
    sc_trace(mVcdFile, ap_CS_fsm_state16, "ap_CS_fsm_state16");
    sc_trace(mVcdFile, r_V_1_fu_600_p2, "r_V_1_fu_600_p2");
    sc_trace(mVcdFile, r_V_1_reg_1054, "r_V_1_reg_1054");
    sc_trace(mVcdFile, r_V_2_fu_613_p2, "r_V_2_fu_613_p2");
    sc_trace(mVcdFile, r_V_2_reg_1060, "r_V_2_reg_1060");
    sc_trace(mVcdFile, r_V_2_1_fu_627_p2, "r_V_2_1_fu_627_p2");
    sc_trace(mVcdFile, r_V_2_1_reg_1066, "r_V_2_1_reg_1066");
    sc_trace(mVcdFile, r_V_2_2_fu_640_p2, "r_V_2_2_fu_640_p2");
    sc_trace(mVcdFile, r_V_2_2_reg_1071, "r_V_2_2_reg_1071");
    sc_trace(mVcdFile, tmp7_fu_680_p2, "tmp7_fu_680_p2");
    sc_trace(mVcdFile, tmp7_reg_1076, "tmp7_reg_1076");
    sc_trace(mVcdFile, ap_CS_fsm_state17, "ap_CS_fsm_state17");
    sc_trace(mVcdFile, tmp4_fu_709_p2, "tmp4_fu_709_p2");
    sc_trace(mVcdFile, tmp4_reg_1081, "tmp4_reg_1081");
    sc_trace(mVcdFile, tmp10_fu_728_p2, "tmp10_fu_728_p2");
    sc_trace(mVcdFile, tmp10_reg_1086, "tmp10_reg_1086");
    sc_trace(mVcdFile, tmp14_fu_757_p2, "tmp14_fu_757_p2");
    sc_trace(mVcdFile, tmp14_reg_1091, "tmp14_reg_1091");
    sc_trace(mVcdFile, tmp_5_fu_801_p3, "tmp_5_fu_801_p3");
    sc_trace(mVcdFile, tmp_5_reg_1096, "tmp_5_reg_1096");
    sc_trace(mVcdFile, ap_CS_fsm_state18, "ap_CS_fsm_state18");
    sc_trace(mVcdFile, i_reg_243, "i_reg_243");
    sc_trace(mVcdFile, j_reg_255, "j_reg_255");
    sc_trace(mVcdFile, ap_CS_fsm_state19, "ap_CS_fsm_state19");
    sc_trace(mVcdFile, tmp_16_cast_fu_419_p1, "tmp_16_cast_fu_419_p1");
    sc_trace(mVcdFile, tmp_17_cast_fu_429_p1, "tmp_17_cast_fu_429_p1");
    sc_trace(mVcdFile, tmp_18_cast_fu_439_p1, "tmp_18_cast_fu_439_p1");
    sc_trace(mVcdFile, tmp_19_cast_fu_467_p1, "tmp_19_cast_fu_467_p1");
    sc_trace(mVcdFile, tmp_23_cast_fu_505_p1, "tmp_23_cast_fu_505_p1");
    sc_trace(mVcdFile, tmp_20_cast_fu_514_p1, "tmp_20_cast_fu_514_p1");
    sc_trace(mVcdFile, tmp_24_cast_fu_542_p1, "tmp_24_cast_fu_542_p1");
    sc_trace(mVcdFile, tmp_21_cast_fu_546_p1, "tmp_21_cast_fu_546_p1");
    sc_trace(mVcdFile, tmp_25_cast_fu_564_p1, "tmp_25_cast_fu_564_p1");
    sc_trace(mVcdFile, tmp_22_cast_fu_809_p1, "tmp_22_cast_fu_809_p1");
    sc_trace(mVcdFile, tmp_6_fu_295_p3, "tmp_6_fu_295_p3");
    sc_trace(mVcdFile, tmp_7_fu_307_p3, "tmp_7_fu_307_p3");
    sc_trace(mVcdFile, p_shl_cast_fu_303_p1, "p_shl_cast_fu_303_p1");
    sc_trace(mVcdFile, p_shl1_cast_fu_315_p1, "p_shl1_cast_fu_315_p1");
    sc_trace(mVcdFile, grp_fu_340_p0, "grp_fu_340_p0");
    sc_trace(mVcdFile, grp_fu_340_p1, "grp_fu_340_p1");
    sc_trace(mVcdFile, tmp_9_fu_346_p3, "tmp_9_fu_346_p3");
    sc_trace(mVcdFile, tmp_3_fu_357_p3, "tmp_3_fu_357_p3");
    sc_trace(mVcdFile, p_shl4_cast_fu_353_p1, "p_shl4_cast_fu_353_p1");
    sc_trace(mVcdFile, p_shl5_cast_fu_364_p1, "p_shl5_cast_fu_364_p1");
    sc_trace(mVcdFile, tmp_12_fu_380_p3, "tmp_12_fu_380_p3");
    sc_trace(mVcdFile, tmp_13_fu_392_p3, "tmp_13_fu_392_p3");
    sc_trace(mVcdFile, p_shl2_cast_fu_388_p1, "p_shl2_cast_fu_388_p1");
    sc_trace(mVcdFile, p_shl3_cast_fu_400_p1, "p_shl3_cast_fu_400_p1");
    sc_trace(mVcdFile, j_cast_cast_fu_410_p1, "j_cast_cast_fu_410_p1");
    sc_trace(mVcdFile, tmp_15_fu_414_p2, "tmp_15_fu_414_p2");
    sc_trace(mVcdFile, tmp_16_fu_424_p2, "tmp_16_fu_424_p2");
    sc_trace(mVcdFile, tmp_17_fu_434_p2, "tmp_17_fu_434_p2");
    sc_trace(mVcdFile, tmp_18_fu_462_p2, "tmp_18_fu_462_p2");
    sc_trace(mVcdFile, tmp_2_cast_cast6_fu_456_p1, "tmp_2_cast_cast6_fu_456_p1");
    sc_trace(mVcdFile, r_V_fu_491_p0, "r_V_fu_491_p0");
    sc_trace(mVcdFile, r_V_fu_491_p1, "r_V_fu_491_p1");
    sc_trace(mVcdFile, tmp_22_fu_500_p2, "tmp_22_fu_500_p2");
    sc_trace(mVcdFile, tmp_19_fu_510_p2, "tmp_19_fu_510_p2");
    sc_trace(mVcdFile, r_V_1_2_fu_558_p0, "r_V_1_2_fu_558_p0");
    sc_trace(mVcdFile, r_V_1_2_fu_558_p1, "r_V_1_2_fu_558_p1");
    sc_trace(mVcdFile, r_V_0_2_fu_587_p0, "r_V_0_2_fu_587_p0");
    sc_trace(mVcdFile, r_V_0_2_fu_587_p1, "r_V_0_2_fu_587_p1");
    sc_trace(mVcdFile, r_V_1_fu_600_p0, "r_V_1_fu_600_p0");
    sc_trace(mVcdFile, r_V_1_fu_600_p1, "r_V_1_fu_600_p1");
    sc_trace(mVcdFile, r_V_2_fu_613_p0, "r_V_2_fu_613_p0");
    sc_trace(mVcdFile, r_V_2_fu_613_p1, "r_V_2_fu_613_p1");
    sc_trace(mVcdFile, r_V_2_1_fu_627_p0, "r_V_2_1_fu_627_p0");
    sc_trace(mVcdFile, r_V_2_1_fu_627_p1, "r_V_2_1_fu_627_p1");
    sc_trace(mVcdFile, r_V_2_2_fu_640_p0, "r_V_2_2_fu_640_p0");
    sc_trace(mVcdFile, r_V_2_2_fu_640_p1, "r_V_2_2_fu_640_p1");
    sc_trace(mVcdFile, tmp_1_cast_fu_649_p1, "tmp_1_cast_fu_649_p1");
    sc_trace(mVcdFile, tmp_0_2_cast_fu_646_p1, "tmp_0_2_cast_fu_646_p1");
    sc_trace(mVcdFile, tmp9_fu_670_p2, "tmp9_fu_670_p2");
    sc_trace(mVcdFile, tmp8_cast_fu_667_p1, "tmp8_cast_fu_667_p1");
    sc_trace(mVcdFile, tmp9_cast_fu_676_p1, "tmp9_cast_fu_676_p1");
    sc_trace(mVcdFile, tmp_2_2_cast_fu_664_p1, "tmp_2_2_cast_fu_664_p1");
    sc_trace(mVcdFile, tmp_2_1_cast_fu_661_p1, "tmp_2_1_cast_fu_661_p1");
    sc_trace(mVcdFile, tmp2_fu_689_p2, "tmp2_fu_689_p2");
    sc_trace(mVcdFile, tmp_2_cast_fu_655_p1, "tmp_2_cast_fu_655_p1");
    sc_trace(mVcdFile, tmp13_cast_fu_695_p1, "tmp13_cast_fu_695_p1");
    sc_trace(mVcdFile, tmp3_fu_699_p2, "tmp3_fu_699_p2");
    sc_trace(mVcdFile, tmp11_cast_fu_686_p1, "tmp11_cast_fu_686_p1");
    sc_trace(mVcdFile, tmp12_cast_fu_705_p1, "tmp12_cast_fu_705_p1");
    sc_trace(mVcdFile, tmp_15_cast_fu_658_p1, "tmp_15_cast_fu_658_p1");
    sc_trace(mVcdFile, tmp5_fu_715_p2, "tmp5_fu_715_p2");
    sc_trace(mVcdFile, tmp15_cast_fu_721_p1, "tmp15_cast_fu_721_p1");
    sc_trace(mVcdFile, tmp16_cast_fu_725_p1, "tmp16_cast_fu_725_p1");
    sc_trace(mVcdFile, tmp12_fu_737_p2, "tmp12_fu_737_p2");
    sc_trace(mVcdFile, tmp_8_cast_fu_652_p1, "tmp_8_cast_fu_652_p1");
    sc_trace(mVcdFile, tmp20_cast_fu_743_p1, "tmp20_cast_fu_743_p1");
    sc_trace(mVcdFile, tmp13_fu_747_p2, "tmp13_fu_747_p2");
    sc_trace(mVcdFile, tmp18_cast_fu_734_p1, "tmp18_cast_fu_734_p1");
    sc_trace(mVcdFile, tmp19_cast_fu_753_p1, "tmp19_cast_fu_753_p1");
    sc_trace(mVcdFile, tmp7_cast_fu_763_p1, "tmp7_cast_fu_763_p1");
    sc_trace(mVcdFile, tmp10_cast_fu_766_p1, "tmp10_cast_fu_766_p1");
    sc_trace(mVcdFile, temp_result_V_1_2_2_fu_769_p2, "temp_result_V_1_2_2_fu_769_p2");
    sc_trace(mVcdFile, tmp14_cast_fu_783_p1, "tmp14_cast_fu_783_p1");
    sc_trace(mVcdFile, tmp17_cast_fu_786_p1, "tmp17_cast_fu_786_p1");
    sc_trace(mVcdFile, tmp_s_fu_789_p2, "tmp_s_fu_789_p2");
    sc_trace(mVcdFile, tmp_25_fu_775_p3, "tmp_25_fu_775_p3");
    sc_trace(mVcdFile, tmp_4_fu_795_p2, "tmp_4_fu_795_p2");
    sc_trace(mVcdFile, grp_fu_813_p1, "grp_fu_813_p1");
    sc_trace(mVcdFile, grp_fu_821_p1, "grp_fu_821_p1");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, grp_fu_340_p00, "grp_fu_340_p00");
    sc_trace(mVcdFile, grp_fu_813_p10, "grp_fu_813_p10");
    sc_trace(mVcdFile, grp_fu_821_p10, "grp_fu_821_p10");
    sc_trace(mVcdFile, r_V_0_2_fu_587_p10, "r_V_0_2_fu_587_p10");
    sc_trace(mVcdFile, r_V_1_2_fu_558_p10, "r_V_1_2_fu_558_p10");
    sc_trace(mVcdFile, r_V_1_fu_600_p10, "r_V_1_fu_600_p10");
    sc_trace(mVcdFile, r_V_2_1_fu_627_p10, "r_V_2_1_fu_627_p10");
    sc_trace(mVcdFile, r_V_2_2_fu_640_p10, "r_V_2_2_fu_640_p10");
    sc_trace(mVcdFile, r_V_2_fu_613_p10, "r_V_2_fu_613_p10");
    sc_trace(mVcdFile, r_V_fu_491_p10, "r_V_fu_491_p10");
#endif

    }
    mHdltvinHandle.open("differentiate.hdltvin.dat");
    mHdltvoutHandle.open("differentiate.hdltvout.dat");
}

differentiate::~differentiate() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    mHdltvinHandle << "] " << endl;
    mHdltvoutHandle << "] " << endl;
    mHdltvinHandle.close();
    mHdltvoutHandle.close();
    delete differentiate_diff_io_s_axi_U;
    delete differentiate_mulbkb_U0;
    delete differentiate_maccud_U1;
    delete differentiate_maccud_U2;
}

void differentiate::thread_ap_var_for_const0() {
    ap_var_for_const0 = ap_const_logic_1;
}

void differentiate::thread_ap_clk_no_reset_() {
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
         esl_seteq<1,1,1>(exitcond2_fu_444_p2.read(), ap_const_lv1_1))) {
        i_reg_243 = i_1_reg_908.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        i_reg_243 = ap_const_lv6_1;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state19.read())) {
        j_reg_255 = j_1_reg_960.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        j_reg_255 = ap_const_lv6_1;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        i_1_reg_908 = i_1_fu_374_p2.read();
        tmp_10_reg_896 = tmp_10_fu_368_p2.read();
        tmp_11_reg_903 = grp_fu_340_p2.read();
        tmp_14_reg_913 = tmp_14_fu_404_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        img_addr_1_reg_920 =  (sc_lv<12>) (tmp_16_cast_fu_419_p1.read());
        img_addr_4_reg_925 =  (sc_lv<12>) (tmp_17_cast_fu_429_p1.read());
        img_addr_7_reg_930 =  (sc_lv<12>) (tmp_18_cast_fu_439_p1.read());
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        img_load_3_reg_1008 = img_q0.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read())) {
        img_load_8_reg_1044 = img_q0.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        j_1_cast_cast_reg_971 = j_1_cast_cast_fu_497_p1.read();
        r_V_reg_966 = r_V_fu_491_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        j_1_reg_960 = j_1_fu_477_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read())) {
        r_V_0_2_reg_1049 = r_V_0_2_fu_587_p2.read();
        r_V_1_reg_1054 = r_V_1_fu_600_p2.read();
        r_V_2_1_reg_1066 = r_V_2_1_fu_627_p2.read();
        r_V_2_2_reg_1071 = r_V_2_2_fu_640_p2.read();
        r_V_2_reg_1060 = r_V_2_fu_613_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read())) {
        r_V_1_2_reg_1028 = r_V_1_2_fu_558_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) || esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()))) {
        reg_267 = window_V_q0.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) || esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) || esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()))) {
        reg_271 = img_q0.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) || esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()))) {
        reg_275 = window_V_q0.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()) || esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read()))) {
        reg_279 = window_V_q0.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read()) || esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()))) {
        reg_283 = img_q0.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()) || esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read()))) {
        reg_287 = window_V_q0.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read()) || esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read()))) {
        reg_291 = img_q0.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state17.read())) {
        tmp10_reg_1086 = tmp10_fu_728_p2.read();
        tmp14_reg_1091 = tmp14_fu_757_p2.read();
        tmp4_reg_1081 = tmp4_fu_709_p2.read();
        tmp7_reg_1076 = tmp7_fu_680_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read())) {
        tmp1_reg_1038 = grp_fu_821_p3.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        tmp8_reg_1002 = grp_fu_813_p3.read();
        tmp_20_reg_987 = tmp_20_fu_519_p2.read();
        tmp_23_reg_992 = tmp_23_fu_534_p2.read();
        tmp_24_reg_997 = tmp_24_fu_538_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        tmp_21_reg_955 = tmp_21_fu_472_p2.read();
        tmp_2_cast_cast_reg_944 = tmp_2_cast_cast_fu_459_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond2_fu_444_p2.read()))) {
        tmp_2_reg_938 = tmp_2_fu_450_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state18.read())) {
        tmp_5_reg_1096 = tmp_5_fu_801_p3.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        tmp_8_reg_874 = tmp_8_fu_319_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(exitcond1_fu_325_p2.read(), ap_const_lv1_0))) {
        tmp_reg_884 = tmp_fu_331_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read())) {
        window_V_load_6_reg_1023 = window_V_q0.read();
    }
}

void differentiate::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void differentiate::thread_ap_CS_fsm_state10() {
    ap_CS_fsm_state10 = ap_CS_fsm.read()[9];
}

void differentiate::thread_ap_CS_fsm_state11() {
    ap_CS_fsm_state11 = ap_CS_fsm.read()[10];
}

void differentiate::thread_ap_CS_fsm_state12() {
    ap_CS_fsm_state12 = ap_CS_fsm.read()[11];
}

void differentiate::thread_ap_CS_fsm_state13() {
    ap_CS_fsm_state13 = ap_CS_fsm.read()[12];
}

void differentiate::thread_ap_CS_fsm_state14() {
    ap_CS_fsm_state14 = ap_CS_fsm.read()[13];
}

void differentiate::thread_ap_CS_fsm_state15() {
    ap_CS_fsm_state15 = ap_CS_fsm.read()[14];
}

void differentiate::thread_ap_CS_fsm_state16() {
    ap_CS_fsm_state16 = ap_CS_fsm.read()[15];
}

void differentiate::thread_ap_CS_fsm_state17() {
    ap_CS_fsm_state17 = ap_CS_fsm.read()[16];
}

void differentiate::thread_ap_CS_fsm_state18() {
    ap_CS_fsm_state18 = ap_CS_fsm.read()[17];
}

void differentiate::thread_ap_CS_fsm_state19() {
    ap_CS_fsm_state19 = ap_CS_fsm.read()[18];
}

void differentiate::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void differentiate::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void differentiate::thread_ap_CS_fsm_state4() {
    ap_CS_fsm_state4 = ap_CS_fsm.read()[3];
}

void differentiate::thread_ap_CS_fsm_state5() {
    ap_CS_fsm_state5 = ap_CS_fsm.read()[4];
}

void differentiate::thread_ap_CS_fsm_state6() {
    ap_CS_fsm_state6 = ap_CS_fsm.read()[5];
}

void differentiate::thread_ap_CS_fsm_state7() {
    ap_CS_fsm_state7 = ap_CS_fsm.read()[6];
}

void differentiate::thread_ap_CS_fsm_state8() {
    ap_CS_fsm_state8 = ap_CS_fsm.read()[7];
}

void differentiate::thread_ap_CS_fsm_state9() {
    ap_CS_fsm_state9 = ap_CS_fsm.read()[8];
}

void differentiate::thread_ap_done() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(exitcond1_fu_325_p2.read(), ap_const_lv1_1))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void differentiate::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void differentiate::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(exitcond1_fu_325_p2.read(), ap_const_lv1_1))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void differentiate::thread_ap_rst_n_inv() {
    ap_rst_n_inv =  (sc_logic) (~ap_rst_n.read());
}

void differentiate::thread_exitcond1_fu_325_p2() {
    exitcond1_fu_325_p2 = (!i_reg_243.read().is_01() || !ap_const_lv6_3F.is_01())? sc_lv<1>(): sc_lv<1>(i_reg_243.read() == ap_const_lv6_3F);
}

void differentiate::thread_exitcond2_fu_444_p2() {
    exitcond2_fu_444_p2 = (!j_reg_255.read().is_01() || !ap_const_lv6_2F.is_01())? sc_lv<1>(): sc_lv<1>(j_reg_255.read() == ap_const_lv6_2F);
}

void differentiate::thread_grp_fu_340_p0() {
    grp_fu_340_p0 =  (sc_lv<6>) (grp_fu_340_p00.read());
}

void differentiate::thread_grp_fu_340_p00() {
    grp_fu_340_p00 = esl_zext<12,6>(tmp_reg_884.read());
}

void differentiate::thread_grp_fu_340_p1() {
    grp_fu_340_p1 =  (sc_lv<7>) (ap_const_lv12_2E);
}

void differentiate::thread_grp_fu_813_p1() {
    grp_fu_813_p1 =  (sc_lv<8>) (grp_fu_813_p10.read());
}

void differentiate::thread_grp_fu_813_p10() {
    grp_fu_813_p10 = esl_zext<11,8>(reg_271.read());
}

void differentiate::thread_grp_fu_821_p1() {
    grp_fu_821_p1 =  (sc_lv<8>) (grp_fu_821_p10.read());
}

void differentiate::thread_grp_fu_821_p10() {
    grp_fu_821_p10 = esl_zext<11,8>(reg_283.read());
}

void differentiate::thread_i_1_fu_374_p2() {
    i_1_fu_374_p2 = (!i_reg_243.read().is_01() || !ap_const_lv6_1.is_01())? sc_lv<6>(): (sc_biguint<6>(i_reg_243.read()) + sc_biguint<6>(ap_const_lv6_1));
}

void differentiate::thread_img_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read())) {
        img_address0 =  (sc_lv<12>) (tmp_25_cast_fu_564_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read())) {
        img_address0 = img_addr_7_reg_930.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read())) {
        img_address0 =  (sc_lv<12>) (tmp_21_cast_fu_546_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read())) {
        img_address0 =  (sc_lv<12>) (tmp_24_cast_fu_542_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        img_address0 = img_addr_4_reg_925.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        img_address0 =  (sc_lv<12>) (tmp_20_cast_fu_514_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        img_address0 =  (sc_lv<12>) (tmp_23_cast_fu_505_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        img_address0 = img_addr_1_reg_920.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        img_address0 =  (sc_lv<12>) (tmp_19_cast_fu_467_p1.read());
    } else {
        img_address0 = "XXXXXXXXXXXX";
    }
}

void differentiate::thread_img_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read()))) {
        img_ce0 = ap_const_logic_1;
    } else {
        img_ce0 = ap_const_logic_0;
    }
}

void differentiate::thread_j_1_cast_cast_fu_497_p1() {
    j_1_cast_cast_fu_497_p1 = esl_zext<13,6>(j_1_reg_960.read());
}

void differentiate::thread_j_1_fu_477_p2() {
    j_1_fu_477_p2 = (!j_reg_255.read().is_01() || !ap_const_lv6_1.is_01())? sc_lv<6>(): (sc_biguint<6>(j_reg_255.read()) + sc_biguint<6>(ap_const_lv6_1));
}

void differentiate::thread_j_cast_cast_fu_410_p1() {
    j_cast_cast_fu_410_p1 = esl_zext<13,6>(j_reg_255.read());
}

void differentiate::thread_p_shl1_cast_fu_315_p1() {
    p_shl1_cast_fu_315_p1 = esl_zext<13,10>(tmp_7_fu_307_p3.read());
}

void differentiate::thread_p_shl2_cast_fu_388_p1() {
    p_shl2_cast_fu_388_p1 = esl_zext<13,12>(tmp_12_fu_380_p3.read());
}

void differentiate::thread_p_shl3_cast_fu_400_p1() {
    p_shl3_cast_fu_400_p1 = esl_zext<13,10>(tmp_13_fu_392_p3.read());
}

void differentiate::thread_p_shl4_cast_fu_353_p1() {
    p_shl4_cast_fu_353_p1 = esl_zext<13,12>(tmp_9_fu_346_p3.read());
}

void differentiate::thread_p_shl5_cast_fu_364_p1() {
    p_shl5_cast_fu_364_p1 = esl_zext<13,10>(tmp_3_fu_357_p3.read());
}

void differentiate::thread_p_shl_cast_fu_303_p1() {
    p_shl_cast_fu_303_p1 = esl_zext<13,12>(tmp_6_fu_295_p3.read());
}

void differentiate::thread_r_V_0_2_fu_587_p0() {
    r_V_0_2_fu_587_p0 = reg_267.read();
}

void differentiate::thread_r_V_0_2_fu_587_p1() {
    r_V_0_2_fu_587_p1 =  (sc_lv<8>) (r_V_0_2_fu_587_p10.read());
}

void differentiate::thread_r_V_0_2_fu_587_p10() {
    r_V_0_2_fu_587_p10 = esl_zext<11,8>(reg_271.read());
}

void differentiate::thread_r_V_0_2_fu_587_p2() {
    r_V_0_2_fu_587_p2 = (!r_V_0_2_fu_587_p0.read().is_01() || !r_V_0_2_fu_587_p1.read().is_01())? sc_lv<11>(): sc_bigint<3>(r_V_0_2_fu_587_p0.read()) * sc_biguint<8>(r_V_0_2_fu_587_p1.read());
}

void differentiate::thread_r_V_1_2_fu_558_p0() {
    r_V_1_2_fu_558_p0 = reg_287.read();
}

void differentiate::thread_r_V_1_2_fu_558_p1() {
    r_V_1_2_fu_558_p1 =  (sc_lv<8>) (r_V_1_2_fu_558_p10.read());
}

void differentiate::thread_r_V_1_2_fu_558_p10() {
    r_V_1_2_fu_558_p10 = esl_zext<11,8>(reg_291.read());
}

void differentiate::thread_r_V_1_2_fu_558_p2() {
    r_V_1_2_fu_558_p2 = (!r_V_1_2_fu_558_p0.read().is_01() || !r_V_1_2_fu_558_p1.read().is_01())? sc_lv<11>(): sc_bigint<3>(r_V_1_2_fu_558_p0.read()) * sc_biguint<8>(r_V_1_2_fu_558_p1.read());
}

void differentiate::thread_r_V_1_fu_600_p0() {
    r_V_1_fu_600_p0 = reg_275.read();
}

void differentiate::thread_r_V_1_fu_600_p1() {
    r_V_1_fu_600_p1 =  (sc_lv<8>) (r_V_1_fu_600_p10.read());
}

void differentiate::thread_r_V_1_fu_600_p10() {
    r_V_1_fu_600_p10 = esl_zext<11,8>(img_load_3_reg_1008.read());
}

void differentiate::thread_r_V_1_fu_600_p2() {
    r_V_1_fu_600_p2 = (!r_V_1_fu_600_p0.read().is_01() || !r_V_1_fu_600_p1.read().is_01())? sc_lv<11>(): sc_bigint<3>(r_V_1_fu_600_p0.read()) * sc_biguint<8>(r_V_1_fu_600_p1.read());
}

void differentiate::thread_r_V_2_1_fu_627_p0() {
    r_V_2_1_fu_627_p0 = reg_287.read();
}

void differentiate::thread_r_V_2_1_fu_627_p1() {
    r_V_2_1_fu_627_p1 =  (sc_lv<8>) (r_V_2_1_fu_627_p10.read());
}

void differentiate::thread_r_V_2_1_fu_627_p10() {
    r_V_2_1_fu_627_p10 = esl_zext<11,8>(reg_283.read());
}

void differentiate::thread_r_V_2_1_fu_627_p2() {
    r_V_2_1_fu_627_p2 = (!r_V_2_1_fu_627_p0.read().is_01() || !r_V_2_1_fu_627_p1.read().is_01())? sc_lv<11>(): sc_bigint<3>(r_V_2_1_fu_627_p0.read()) * sc_biguint<8>(r_V_2_1_fu_627_p1.read());
}

void differentiate::thread_r_V_2_2_fu_640_p0() {
    r_V_2_2_fu_640_p0 = reg_279.read();
}

void differentiate::thread_r_V_2_2_fu_640_p1() {
    r_V_2_2_fu_640_p1 =  (sc_lv<8>) (r_V_2_2_fu_640_p10.read());
}

void differentiate::thread_r_V_2_2_fu_640_p10() {
    r_V_2_2_fu_640_p10 = esl_zext<11,8>(img_load_8_reg_1044.read());
}

void differentiate::thread_r_V_2_2_fu_640_p2() {
    r_V_2_2_fu_640_p2 = (!r_V_2_2_fu_640_p0.read().is_01() || !r_V_2_2_fu_640_p1.read().is_01())? sc_lv<11>(): sc_bigint<3>(r_V_2_2_fu_640_p0.read()) * sc_biguint<8>(r_V_2_2_fu_640_p1.read());
}

void differentiate::thread_r_V_2_fu_613_p0() {
    r_V_2_fu_613_p0 = window_V_load_6_reg_1023.read();
}

void differentiate::thread_r_V_2_fu_613_p1() {
    r_V_2_fu_613_p1 =  (sc_lv<8>) (r_V_2_fu_613_p10.read());
}

void differentiate::thread_r_V_2_fu_613_p10() {
    r_V_2_fu_613_p10 = esl_zext<11,8>(reg_291.read());
}

void differentiate::thread_r_V_2_fu_613_p2() {
    r_V_2_fu_613_p2 = (!r_V_2_fu_613_p0.read().is_01() || !r_V_2_fu_613_p1.read().is_01())? sc_lv<11>(): sc_bigint<3>(r_V_2_fu_613_p0.read()) * sc_biguint<8>(r_V_2_fu_613_p1.read());
}

void differentiate::thread_r_V_fu_491_p0() {
    r_V_fu_491_p0 = reg_267.read();
}

void differentiate::thread_r_V_fu_491_p1() {
    r_V_fu_491_p1 =  (sc_lv<8>) (r_V_fu_491_p10.read());
}

void differentiate::thread_r_V_fu_491_p10() {
    r_V_fu_491_p10 = esl_zext<11,8>(reg_271.read());
}

void differentiate::thread_r_V_fu_491_p2() {
    r_V_fu_491_p2 = (!r_V_fu_491_p0.read().is_01() || !r_V_fu_491_p1.read().is_01())? sc_lv<11>(): sc_bigint<3>(r_V_fu_491_p0.read()) * sc_biguint<8>(r_V_fu_491_p1.read());
}

void differentiate::thread_res_V_address0() {
    res_V_address0 =  (sc_lv<12>) (tmp_22_cast_fu_809_p1.read());
}

void differentiate::thread_res_V_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state19.read())) {
        res_V_ce0 = ap_const_logic_1;
    } else {
        res_V_ce0 = ap_const_logic_0;
    }
}

void differentiate::thread_res_V_d0() {
    res_V_d0 = tmp_5_reg_1096.read();
}

void differentiate::thread_res_V_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state19.read())) {
        res_V_we0 = ap_const_logic_1;
    } else {
        res_V_we0 = ap_const_logic_0;
    }
}

void differentiate::thread_temp_result_V_1_2_2_fu_769_p2() {
    temp_result_V_1_2_2_fu_769_p2 = (!tmp7_cast_fu_763_p1.read().is_01() || !tmp10_cast_fu_766_p1.read().is_01())? sc_lv<15>(): (sc_bigint<15>(tmp7_cast_fu_763_p1.read()) + sc_bigint<15>(tmp10_cast_fu_766_p1.read()));
}

void differentiate::thread_tmp10_cast_fu_766_p1() {
    tmp10_cast_fu_766_p1 = esl_sext<15,14>(tmp4_reg_1081.read());
}

void differentiate::thread_tmp10_fu_728_p2() {
    tmp10_fu_728_p2 = (!tmp15_cast_fu_721_p1.read().is_01() || !tmp16_cast_fu_725_p1.read().is_01())? sc_lv<13>(): (sc_bigint<13>(tmp15_cast_fu_721_p1.read()) + sc_bigint<13>(tmp16_cast_fu_725_p1.read()));
}

void differentiate::thread_tmp11_cast_fu_686_p1() {
    tmp11_cast_fu_686_p1 = esl_sext<14,12>(tmp1_reg_1038.read());
}

void differentiate::thread_tmp12_cast_fu_705_p1() {
    tmp12_cast_fu_705_p1 = esl_sext<14,13>(tmp3_fu_699_p2.read());
}

void differentiate::thread_tmp12_fu_737_p2() {
    tmp12_fu_737_p2 = (!tmp_2_2_cast_fu_664_p1.read().is_01() || !tmp_0_2_cast_fu_646_p1.read().is_01())? sc_lv<12>(): (sc_bigint<12>(tmp_2_2_cast_fu_664_p1.read()) + sc_bigint<12>(tmp_0_2_cast_fu_646_p1.read()));
}

void differentiate::thread_tmp13_cast_fu_695_p1() {
    tmp13_cast_fu_695_p1 = esl_sext<13,12>(tmp2_fu_689_p2.read());
}

void differentiate::thread_tmp13_fu_747_p2() {
    tmp13_fu_747_p2 = (!tmp_8_cast_fu_652_p1.read().is_01() || !tmp20_cast_fu_743_p1.read().is_01())? sc_lv<13>(): (sc_bigint<13>(tmp_8_cast_fu_652_p1.read()) + sc_bigint<13>(tmp20_cast_fu_743_p1.read()));
}

void differentiate::thread_tmp14_cast_fu_783_p1() {
    tmp14_cast_fu_783_p1 = esl_sext<15,13>(tmp10_reg_1086.read());
}

void differentiate::thread_tmp14_fu_757_p2() {
    tmp14_fu_757_p2 = (!tmp18_cast_fu_734_p1.read().is_01() || !tmp19_cast_fu_753_p1.read().is_01())? sc_lv<14>(): (sc_bigint<14>(tmp18_cast_fu_734_p1.read()) + sc_bigint<14>(tmp19_cast_fu_753_p1.read()));
}

void differentiate::thread_tmp15_cast_fu_721_p1() {
    tmp15_cast_fu_721_p1 = esl_sext<13,12>(tmp5_fu_715_p2.read());
}

void differentiate::thread_tmp16_cast_fu_725_p1() {
    tmp16_cast_fu_725_p1 = esl_sext<13,12>(tmp1_reg_1038.read());
}

void differentiate::thread_tmp17_cast_fu_786_p1() {
    tmp17_cast_fu_786_p1 = esl_sext<15,14>(tmp14_reg_1091.read());
}

void differentiate::thread_tmp18_cast_fu_734_p1() {
    tmp18_cast_fu_734_p1 = esl_sext<14,12>(tmp8_reg_1002.read());
}

void differentiate::thread_tmp19_cast_fu_753_p1() {
    tmp19_cast_fu_753_p1 = esl_sext<14,13>(tmp13_fu_747_p2.read());
}

void differentiate::thread_tmp20_cast_fu_743_p1() {
    tmp20_cast_fu_743_p1 = esl_sext<13,12>(tmp12_fu_737_p2.read());
}

void differentiate::thread_tmp2_fu_689_p2() {
    tmp2_fu_689_p2 = (!tmp_2_2_cast_fu_664_p1.read().is_01() || !tmp_2_1_cast_fu_661_p1.read().is_01())? sc_lv<12>(): (sc_bigint<12>(tmp_2_2_cast_fu_664_p1.read()) + sc_bigint<12>(tmp_2_1_cast_fu_661_p1.read()));
}

void differentiate::thread_tmp3_fu_699_p2() {
    tmp3_fu_699_p2 = (!tmp_2_cast_fu_655_p1.read().is_01() || !tmp13_cast_fu_695_p1.read().is_01())? sc_lv<13>(): (sc_bigint<13>(tmp_2_cast_fu_655_p1.read()) + sc_bigint<13>(tmp13_cast_fu_695_p1.read()));
}

void differentiate::thread_tmp4_fu_709_p2() {
    tmp4_fu_709_p2 = (!tmp11_cast_fu_686_p1.read().is_01() || !tmp12_cast_fu_705_p1.read().is_01())? sc_lv<14>(): (sc_bigint<14>(tmp11_cast_fu_686_p1.read()) + sc_bigint<14>(tmp12_cast_fu_705_p1.read()));
}

void differentiate::thread_tmp5_fu_715_p2() {
    tmp5_fu_715_p2 = (!tmp_2_1_cast_fu_661_p1.read().is_01() || !tmp_15_cast_fu_658_p1.read().is_01())? sc_lv<12>(): (sc_bigint<12>(tmp_2_1_cast_fu_661_p1.read()) + sc_bigint<12>(tmp_15_cast_fu_658_p1.read()));
}

void differentiate::thread_tmp7_cast_fu_763_p1() {
    tmp7_cast_fu_763_p1 = esl_sext<15,13>(tmp7_reg_1076.read());
}

void differentiate::thread_tmp7_fu_680_p2() {
    tmp7_fu_680_p2 = (!tmp8_cast_fu_667_p1.read().is_01() || !tmp9_cast_fu_676_p1.read().is_01())? sc_lv<13>(): (sc_bigint<13>(tmp8_cast_fu_667_p1.read()) + sc_bigint<13>(tmp9_cast_fu_676_p1.read()));
}

void differentiate::thread_tmp8_cast_fu_667_p1() {
    tmp8_cast_fu_667_p1 = esl_sext<13,12>(tmp8_reg_1002.read());
}

void differentiate::thread_tmp9_cast_fu_676_p1() {
    tmp9_cast_fu_676_p1 = esl_sext<13,12>(tmp9_fu_670_p2.read());
}

void differentiate::thread_tmp9_fu_670_p2() {
    tmp9_fu_670_p2 = (!tmp_1_cast_fu_649_p1.read().is_01() || !tmp_0_2_cast_fu_646_p1.read().is_01())? sc_lv<12>(): (sc_bigint<12>(tmp_1_cast_fu_649_p1.read()) + sc_bigint<12>(tmp_0_2_cast_fu_646_p1.read()));
}

void differentiate::thread_tmp_0_2_cast_fu_646_p1() {
    tmp_0_2_cast_fu_646_p1 = esl_sext<12,11>(r_V_0_2_reg_1049.read());
}

void differentiate::thread_tmp_10_fu_368_p2() {
    tmp_10_fu_368_p2 = (!p_shl4_cast_fu_353_p1.read().is_01() || !p_shl5_cast_fu_364_p1.read().is_01())? sc_lv<13>(): (sc_biguint<13>(p_shl4_cast_fu_353_p1.read()) - sc_biguint<13>(p_shl5_cast_fu_364_p1.read()));
}

void differentiate::thread_tmp_12_fu_380_p3() {
    tmp_12_fu_380_p3 = esl_concat<6,6>(i_1_fu_374_p2.read(), ap_const_lv6_0);
}

void differentiate::thread_tmp_13_fu_392_p3() {
    tmp_13_fu_392_p3 = esl_concat<6,4>(i_1_fu_374_p2.read(), ap_const_lv4_0);
}

void differentiate::thread_tmp_14_fu_404_p2() {
    tmp_14_fu_404_p2 = (!p_shl2_cast_fu_388_p1.read().is_01() || !p_shl3_cast_fu_400_p1.read().is_01())? sc_lv<13>(): (sc_biguint<13>(p_shl2_cast_fu_388_p1.read()) - sc_biguint<13>(p_shl3_cast_fu_400_p1.read()));
}

void differentiate::thread_tmp_15_cast_fu_658_p1() {
    tmp_15_cast_fu_658_p1 = esl_sext<12,11>(r_V_2_reg_1060.read());
}

void differentiate::thread_tmp_15_fu_414_p2() {
    tmp_15_fu_414_p2 = (!tmp_10_reg_896.read().is_01() || !j_cast_cast_fu_410_p1.read().is_01())? sc_lv<13>(): (sc_biguint<13>(tmp_10_reg_896.read()) + sc_biguint<13>(j_cast_cast_fu_410_p1.read()));
}

void differentiate::thread_tmp_16_cast_fu_419_p1() {
    tmp_16_cast_fu_419_p1 = esl_sext<32,13>(tmp_15_fu_414_p2.read());
}

void differentiate::thread_tmp_16_fu_424_p2() {
    tmp_16_fu_424_p2 = (!tmp_8_reg_874.read().is_01() || !j_cast_cast_fu_410_p1.read().is_01())? sc_lv<13>(): (sc_biguint<13>(tmp_8_reg_874.read()) + sc_biguint<13>(j_cast_cast_fu_410_p1.read()));
}

void differentiate::thread_tmp_17_cast_fu_429_p1() {
    tmp_17_cast_fu_429_p1 = esl_sext<32,13>(tmp_16_fu_424_p2.read());
}

void differentiate::thread_tmp_17_fu_434_p2() {
    tmp_17_fu_434_p2 = (!tmp_14_reg_913.read().is_01() || !j_cast_cast_fu_410_p1.read().is_01())? sc_lv<13>(): (sc_biguint<13>(tmp_14_reg_913.read()) + sc_biguint<13>(j_cast_cast_fu_410_p1.read()));
}

void differentiate::thread_tmp_18_cast_fu_439_p1() {
    tmp_18_cast_fu_439_p1 = esl_sext<32,13>(tmp_17_fu_434_p2.read());
}

void differentiate::thread_tmp_18_fu_462_p2() {
    tmp_18_fu_462_p2 = (!tmp_10_reg_896.read().is_01() || !tmp_2_cast_cast_fu_459_p1.read().is_01())? sc_lv<13>(): (sc_biguint<13>(tmp_10_reg_896.read()) + sc_biguint<13>(tmp_2_cast_cast_fu_459_p1.read()));
}

void differentiate::thread_tmp_19_cast_fu_467_p1() {
    tmp_19_cast_fu_467_p1 = esl_sext<32,13>(tmp_18_fu_462_p2.read());
}

void differentiate::thread_tmp_19_fu_510_p2() {
    tmp_19_fu_510_p2 = (!tmp_8_reg_874.read().is_01() || !tmp_2_cast_cast_reg_944.read().is_01())? sc_lv<13>(): (sc_biguint<13>(tmp_8_reg_874.read()) + sc_biguint<13>(tmp_2_cast_cast_reg_944.read()));
}

void differentiate::thread_tmp_1_cast_fu_649_p1() {
    tmp_1_cast_fu_649_p1 = esl_sext<12,11>(r_V_1_reg_1054.read());
}

void differentiate::thread_tmp_20_cast_fu_514_p1() {
    tmp_20_cast_fu_514_p1 = esl_sext<32,13>(tmp_19_fu_510_p2.read());
}

void differentiate::thread_tmp_20_fu_519_p2() {
    tmp_20_fu_519_p2 = (!tmp_14_reg_913.read().is_01() || !tmp_2_cast_cast_reg_944.read().is_01())? sc_lv<13>(): (sc_biguint<13>(tmp_14_reg_913.read()) + sc_biguint<13>(tmp_2_cast_cast_reg_944.read()));
}

void differentiate::thread_tmp_21_cast_fu_546_p1() {
    tmp_21_cast_fu_546_p1 = esl_sext<32,13>(tmp_20_reg_987.read());
}

void differentiate::thread_tmp_21_fu_472_p2() {
    tmp_21_fu_472_p2 = (!tmp_11_reg_903.read().is_01() || !tmp_2_cast_cast6_fu_456_p1.read().is_01())? sc_lv<12>(): (sc_biguint<12>(tmp_11_reg_903.read()) + sc_biguint<12>(tmp_2_cast_cast6_fu_456_p1.read()));
}

void differentiate::thread_tmp_22_cast_fu_809_p1() {
    tmp_22_cast_fu_809_p1 = esl_zext<32,12>(tmp_21_reg_955.read());
}

void differentiate::thread_tmp_22_fu_500_p2() {
    tmp_22_fu_500_p2 = (!tmp_10_reg_896.read().is_01() || !j_1_cast_cast_fu_497_p1.read().is_01())? sc_lv<13>(): (sc_biguint<13>(tmp_10_reg_896.read()) + sc_biguint<13>(j_1_cast_cast_fu_497_p1.read()));
}

void differentiate::thread_tmp_23_cast_fu_505_p1() {
    tmp_23_cast_fu_505_p1 = esl_sext<32,13>(tmp_22_fu_500_p2.read());
}

void differentiate::thread_tmp_23_fu_534_p2() {
    tmp_23_fu_534_p2 = (!tmp_8_reg_874.read().is_01() || !j_1_cast_cast_reg_971.read().is_01())? sc_lv<13>(): (sc_biguint<13>(tmp_8_reg_874.read()) + sc_biguint<13>(j_1_cast_cast_reg_971.read()));
}

void differentiate::thread_tmp_24_cast_fu_542_p1() {
    tmp_24_cast_fu_542_p1 = esl_sext<32,13>(tmp_23_reg_992.read());
}

void differentiate::thread_tmp_24_fu_538_p2() {
    tmp_24_fu_538_p2 = (!tmp_14_reg_913.read().is_01() || !j_1_cast_cast_reg_971.read().is_01())? sc_lv<13>(): (sc_biguint<13>(tmp_14_reg_913.read()) + sc_biguint<13>(j_1_cast_cast_reg_971.read()));
}

void differentiate::thread_tmp_25_cast_fu_564_p1() {
    tmp_25_cast_fu_564_p1 = esl_sext<32,13>(tmp_24_reg_997.read());
}

void differentiate::thread_tmp_25_fu_775_p3() {
    tmp_25_fu_775_p3 = temp_result_V_1_2_2_fu_769_p2.read().range(14, 14);
}

void differentiate::thread_tmp_2_1_cast_fu_661_p1() {
    tmp_2_1_cast_fu_661_p1 = esl_sext<12,11>(r_V_2_1_reg_1066.read());
}

void differentiate::thread_tmp_2_2_cast_fu_664_p1() {
    tmp_2_2_cast_fu_664_p1 = esl_sext<12,11>(r_V_2_2_reg_1071.read());
}

void differentiate::thread_tmp_2_cast_cast6_fu_456_p1() {
    tmp_2_cast_cast6_fu_456_p1 = esl_zext<12,6>(tmp_2_reg_938.read());
}

void differentiate::thread_tmp_2_cast_cast_fu_459_p1() {
    tmp_2_cast_cast_fu_459_p1 = esl_zext<13,6>(tmp_2_reg_938.read());
}

void differentiate::thread_tmp_2_cast_fu_655_p1() {
    tmp_2_cast_fu_655_p1 = esl_sext<13,11>(r_V_2_reg_1060.read());
}

void differentiate::thread_tmp_2_fu_450_p2() {
    tmp_2_fu_450_p2 = (!j_reg_255.read().is_01() || !ap_const_lv6_3F.is_01())? sc_lv<6>(): (sc_biguint<6>(j_reg_255.read()) + sc_bigint<6>(ap_const_lv6_3F));
}

void differentiate::thread_tmp_3_fu_357_p3() {
    tmp_3_fu_357_p3 = esl_concat<6,4>(tmp_reg_884.read(), ap_const_lv4_0);
}

void differentiate::thread_tmp_4_fu_795_p2() {
    tmp_4_fu_795_p2 = (!ap_const_lv15_0.is_01() || !tmp_s_fu_789_p2.read().is_01())? sc_lv<15>(): (sc_biguint<15>(ap_const_lv15_0) - sc_biguint<15>(tmp_s_fu_789_p2.read()));
}

void differentiate::thread_tmp_5_fu_801_p3() {
    tmp_5_fu_801_p3 = (!tmp_25_fu_775_p3.read()[0].is_01())? sc_lv<15>(): ((tmp_25_fu_775_p3.read()[0].to_bool())? tmp_4_fu_795_p2.read(): tmp_s_fu_789_p2.read());
}

void differentiate::thread_tmp_6_fu_295_p3() {
    tmp_6_fu_295_p3 = esl_concat<6,6>(i_reg_243.read(), ap_const_lv6_0);
}

void differentiate::thread_tmp_7_fu_307_p3() {
    tmp_7_fu_307_p3 = esl_concat<6,4>(i_reg_243.read(), ap_const_lv4_0);
}

void differentiate::thread_tmp_8_cast_fu_652_p1() {
    tmp_8_cast_fu_652_p1 = esl_sext<13,11>(r_V_1_reg_1054.read());
}

void differentiate::thread_tmp_8_fu_319_p2() {
    tmp_8_fu_319_p2 = (!p_shl_cast_fu_303_p1.read().is_01() || !p_shl1_cast_fu_315_p1.read().is_01())? sc_lv<13>(): (sc_biguint<13>(p_shl_cast_fu_303_p1.read()) - sc_biguint<13>(p_shl1_cast_fu_315_p1.read()));
}

void differentiate::thread_tmp_9_fu_346_p3() {
    tmp_9_fu_346_p3 = esl_concat<6,6>(tmp_reg_884.read(), ap_const_lv6_0);
}

void differentiate::thread_tmp_fu_331_p2() {
    tmp_fu_331_p2 = (!i_reg_243.read().is_01() || !ap_const_lv6_3F.is_01())? sc_lv<6>(): (sc_biguint<6>(i_reg_243.read()) + sc_bigint<6>(ap_const_lv6_3F));
}

void differentiate::thread_tmp_s_fu_789_p2() {
    tmp_s_fu_789_p2 = (!tmp14_cast_fu_783_p1.read().is_01() || !tmp17_cast_fu_786_p1.read().is_01())? sc_lv<15>(): (sc_bigint<15>(tmp14_cast_fu_783_p1.read()) + sc_bigint<15>(tmp17_cast_fu_786_p1.read()));
}

void differentiate::thread_window_V_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read())) {
        window_V_address0 =  (sc_lv<4>) (ap_const_lv32_8);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read())) {
        window_V_address0 =  (sc_lv<4>) (ap_const_lv32_7);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read())) {
        window_V_address0 =  (sc_lv<4>) (ap_const_lv32_6);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        window_V_address0 =  (sc_lv<4>) (ap_const_lv32_5);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        window_V_address0 =  (sc_lv<4>) (ap_const_lv32_4);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        window_V_address0 =  (sc_lv<4>) (ap_const_lv32_3);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        window_V_address0 =  (sc_lv<4>) (ap_const_lv32_2);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        window_V_address0 =  (sc_lv<4>) (ap_const_lv32_1);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        window_V_address0 =  (sc_lv<4>) (ap_const_lv32_0);
    } else {
        window_V_address0 =  (sc_lv<4>) ("XXXX");
    }
}

void differentiate::thread_window_V_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()))) {
        window_V_ce0 = ap_const_logic_1;
    } else {
        window_V_ce0 = ap_const_logic_0;
    }
}

void differentiate::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(exitcond1_fu_325_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_state3;
            }
            break;
        case 4 : 
            ap_NS_fsm = ap_ST_fsm_state4;
            break;
        case 8 : 
            ap_NS_fsm = ap_ST_fsm_state5;
            break;
        case 16 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && esl_seteq<1,1,1>(exitcond2_fu_444_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state6;
            }
            break;
        case 32 : 
            ap_NS_fsm = ap_ST_fsm_state7;
            break;
        case 64 : 
            ap_NS_fsm = ap_ST_fsm_state8;
            break;
        case 128 : 
            ap_NS_fsm = ap_ST_fsm_state9;
            break;
        case 256 : 
            ap_NS_fsm = ap_ST_fsm_state10;
            break;
        case 512 : 
            ap_NS_fsm = ap_ST_fsm_state11;
            break;
        case 1024 : 
            ap_NS_fsm = ap_ST_fsm_state12;
            break;
        case 2048 : 
            ap_NS_fsm = ap_ST_fsm_state13;
            break;
        case 4096 : 
            ap_NS_fsm = ap_ST_fsm_state14;
            break;
        case 8192 : 
            ap_NS_fsm = ap_ST_fsm_state15;
            break;
        case 16384 : 
            ap_NS_fsm = ap_ST_fsm_state16;
            break;
        case 32768 : 
            ap_NS_fsm = ap_ST_fsm_state17;
            break;
        case 65536 : 
            ap_NS_fsm = ap_ST_fsm_state18;
            break;
        case 131072 : 
            ap_NS_fsm = ap_ST_fsm_state19;
            break;
        case 262144 : 
            ap_NS_fsm = ap_ST_fsm_state5;
            break;
        default : 
            ap_NS_fsm =  (sc_lv<19>) ("XXXXXXXXXXXXXXXXXXX");
            break;
    }
}

void differentiate::thread_hdltv_gen() {
    const char* dump_tv = std::getenv("AP_WRITE_TV");
    if (!(dump_tv && string(dump_tv) == "on")) return;

    wait();

    mHdltvinHandle << "[ " << endl;
    mHdltvoutHandle << "[ " << endl;
    int ap_cycleNo = 0;
    while (1) {
        wait();
        const char* mComma = ap_cycleNo == 0 ? " " : ", " ;
        mHdltvinHandle << mComma << "{"  <<  " \"ap_rst_n\" :  \"" << ap_rst_n.read() << "\" ";
        mHdltvoutHandle << mComma << "{"  <<  " \"res_V_address0\" :  \"" << res_V_address0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"res_V_ce0\" :  \"" << res_V_ce0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"res_V_we0\" :  \"" << res_V_we0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"res_V_d0\" :  \"" << res_V_d0.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_diff_io_AWVALID\" :  \"" << s_axi_diff_io_AWVALID.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_diff_io_AWREADY\" :  \"" << s_axi_diff_io_AWREADY.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_diff_io_AWADDR\" :  \"" << s_axi_diff_io_AWADDR.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_diff_io_WVALID\" :  \"" << s_axi_diff_io_WVALID.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_diff_io_WREADY\" :  \"" << s_axi_diff_io_WREADY.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_diff_io_WDATA\" :  \"" << s_axi_diff_io_WDATA.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_diff_io_WSTRB\" :  \"" << s_axi_diff_io_WSTRB.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_diff_io_ARVALID\" :  \"" << s_axi_diff_io_ARVALID.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_diff_io_ARREADY\" :  \"" << s_axi_diff_io_ARREADY.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_diff_io_ARADDR\" :  \"" << s_axi_diff_io_ARADDR.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_diff_io_RVALID\" :  \"" << s_axi_diff_io_RVALID.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_diff_io_RREADY\" :  \"" << s_axi_diff_io_RREADY.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_diff_io_RDATA\" :  \"" << s_axi_diff_io_RDATA.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_diff_io_RRESP\" :  \"" << s_axi_diff_io_RRESP.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_diff_io_BVALID\" :  \"" << s_axi_diff_io_BVALID.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_diff_io_BREADY\" :  \"" << s_axi_diff_io_BREADY.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_diff_io_BRESP\" :  \"" << s_axi_diff_io_BRESP.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"interrupt\" :  \"" << interrupt.read() << "\" ";
        mHdltvinHandle << "}" << std::endl;
        mHdltvoutHandle << "}" << std::endl;
        ap_cycleNo++;
    }
}

}

